.TH "DdGen" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdGen
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDdManager\fP * \fBmanager\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int * \fBcube\fP"
.br
.ti -1c
.RI "      CUDD_VALUE_TYPE \fBvalue\fP"
.br
.ti -1c
.RI "   } \fBcubes\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int * \fBcube\fP"
.br
.ti -1c
.RI "      \fBDdNode\fP * \fBub\fP"
.br
.ti -1c
.RI "   } \fBprimes\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBsize\fP"
.br
.ti -1c
.RI "   } \fBnodes\fP"
.br
.ti -1c
.RI "} \fBgen\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBsp\fP"
.br
.ti -1c
.RI "   \fBDdNode\fP ** \fBstack\fP"
.br
.ti -1c
.RI "} \fBstack\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBnode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
