.TH "DdHashTable" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdHashTable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBkeysize\fP"
.br
.ti -1c
.RI "unsigned int \fBitemsize\fP"
.br
.ti -1c
.RI "\fBDdHashItem\fP ** \fBbucket\fP"
.br
.ti -1c
.RI "\fBDdHashItem\fP * \fBnextFree\fP"
.br
.ti -1c
.RI "\fBDdHashItem\fP ** \fBmemoryList\fP"
.br
.ti -1c
.RI "unsigned int \fBnumBuckets\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxsize\fP"
.br
.ti -1c
.RI "\fBDdManager\fP * \fBmanager\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
