.TH "DdLevelQueue" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdLevelQueue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBfirst\fP"
.br
.ti -1c
.RI "\fBDdQueueItem\fP ** \fBlast\fP"
.br
.ti -1c
.RI "\fBDdQueueItem\fP * \fBfreelist\fP"
.br
.ti -1c
.RI "\fBDdQueueItem\fP ** \fBbuckets\fP"
.br
.ti -1c
.RI "int \fBlevels\fP"
.br
.ti -1c
.RI "int \fBitemsize\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBmaxsize\fP"
.br
.ti -1c
.RI "int \fBnumBuckets\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
