.TH "DdLocalCacheItem" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdLocalCacheItem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDdNode\fP * \fBvalue\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBkey\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
