.TH "DdLocalCache" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdLocalCache
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDdLocalCacheItem\fP * \fBitem\fP"
.br
.ti -1c
.RI "unsigned int \fBitemsize\fP"
.br
.ti -1c
.RI "unsigned int \fBkeysize\fP"
.br
.ti -1c
.RI "unsigned int \fBslots\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.ti -1c
.RI "double \fBlookUps\fP"
.br
.ti -1c
.RI "double \fBminHit\fP"
.br
.ti -1c
.RI "double \fBhits\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxslots\fP"
.br
.ti -1c
.RI "\fBDdManager\fP * \fBmanager\fP"
.br
.ti -1c
.RI "struct \fBDdLocalCache\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
