.TH "DdManager" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdManager
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDdNode\fP \fBsentinel\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBone\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBzero\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBplusinfinity\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBminusinfinity\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBbackground\fP"
.br
.ti -1c
.RI "\fBDdCache\fP * \fBacache\fP"
.br
.ti -1c
.RI "\fBDdCache\fP * \fBcache\fP"
.br
.ti -1c
.RI "unsigned int \fBcacheSlots\fP"
.br
.ti -1c
.RI "int \fBcacheShift\fP"
.br
.ti -1c
.RI "double \fBcacheMisses\fP"
.br
.ti -1c
.RI "double \fBcacheHits\fP"
.br
.ti -1c
.RI "double \fBminHit\fP"
.br
.ti -1c
.RI "int \fBcacheSlack\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxCacheHard\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBsizeZ\fP"
.br
.ti -1c
.RI "int \fBmaxSize\fP"
.br
.ti -1c
.RI "int \fBmaxSizeZ\fP"
.br
.ti -1c
.RI "\fBDdSubtable\fP * \fBsubtables\fP"
.br
.ti -1c
.RI "\fBDdSubtable\fP * \fBsubtableZ\fP"
.br
.ti -1c
.RI "\fBDdSubtable\fP \fBconstants\fP"
.br
.ti -1c
.RI "unsigned int \fBslots\fP"
.br
.ti -1c
.RI "unsigned int \fBkeys\fP"
.br
.ti -1c
.RI "unsigned int \fBkeysZ\fP"
.br
.ti -1c
.RI "unsigned int \fBdead\fP"
.br
.ti -1c
.RI "unsigned int \fBdeadZ\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxLive\fP"
.br
.ti -1c
.RI "unsigned int \fBminDead\fP"
.br
.ti -1c
.RI "double \fBgcFrac\fP"
.br
.ti -1c
.RI "int \fBgcEnabled\fP"
.br
.ti -1c
.RI "unsigned int \fBlooseUpTo\fP"
.br
.ti -1c
.RI "unsigned int \fBinitSlots\fP"
.br
.ti -1c
.RI "\fBDdNode\fP ** \fBstack\fP"
.br
.ti -1c
.RI "double \fBallocated\fP"
.br
.ti -1c
.RI "double \fBreclaimed\fP"
.br
.ti -1c
.RI "int \fBisolated\fP"
.br
.ti -1c
.RI "int * \fBperm\fP"
.br
.ti -1c
.RI "int * \fBpermZ\fP"
.br
.ti -1c
.RI "int * \fBinvperm\fP"
.br
.ti -1c
.RI "int * \fBinvpermZ\fP"
.br
.ti -1c
.RI "\fBDdNode\fP ** \fBvars\fP"
.br
.ti -1c
.RI "int * \fBmap\fP"
.br
.ti -1c
.RI "\fBDdNode\fP ** \fBuniv\fP"
.br
.ti -1c
.RI "int \fBlinearSize\fP"
.br
.ti -1c
.RI "long * \fBinteract\fP"
.br
.ti -1c
.RI "long * \fBlinear\fP"
.br
.ti -1c
.RI "\fBDdNode\fP ** \fBmemoryList\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBnextFree\fP"
.br
.ti -1c
.RI "char * \fBstash\fP"
.br
.ti -1c
.RI "\fBDdNode\fP ** \fBdeathRow\fP"
.br
.ti -1c
.RI "int \fBdeathRowDepth\fP"
.br
.ti -1c
.RI "int \fBnextDead\fP"
.br
.ti -1c
.RI "unsigned \fBdeadMask\fP"
.br
.ti -1c
.RI "CUDD_VALUE_TYPE \fBepsilon\fP"
.br
.ti -1c
.RI "int \fBreordered\fP"
.br
.ti -1c
.RI "unsigned int \fBreorderings\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxReorderings\fP"
.br
.ti -1c
.RI "int \fBsiftMaxVar\fP"
.br
.ti -1c
.RI "int \fBsiftMaxSwap\fP"
.br
.ti -1c
.RI "double \fBmaxGrowth\fP"
.br
.ti -1c
.RI "double \fBmaxGrowthAlt\fP"
.br
.ti -1c
.RI "int \fBreordCycle\fP"
.br
.ti -1c
.RI "int \fBautoDyn\fP"
.br
.ti -1c
.RI "int \fBautoDynZ\fP"
.br
.ti -1c
.RI "Cudd_ReorderingType \fBautoMethod\fP"
.br
.ti -1c
.RI "Cudd_ReorderingType \fBautoMethodZ\fP"
.br
.ti -1c
.RI "int \fBrealign\fP"
.br
.ti -1c
.RI "int \fBrealignZ\fP"
.br
.ti -1c
.RI "unsigned int \fBnextDyn\fP"
.br
.ti -1c
.RI "unsigned int \fBcountDead\fP"
.br
.ti -1c
.RI "\fBMtrNode\fP * \fBtree\fP"
.br
.ti -1c
.RI "\fBMtrNode\fP * \fBtreeZ\fP"
.br
.ti -1c
.RI "Cudd_AggregationType \fBgroupcheck\fP"
.br
.ti -1c
.RI "int \fBrecomb\fP"
.br
.ti -1c
.RI "int \fBsymmviolation\fP"
.br
.ti -1c
.RI "int \fBarcviolation\fP"
.br
.ti -1c
.RI "int \fBpopulationSize\fP"
.br
.ti -1c
.RI "int \fBnumberXovers\fP"
.br
.ti -1c
.RI "unsigned int \fBrandomizeOrder\fP"
.br
.ti -1c
.RI "\fBDdLocalCache\fP * \fBlocalCaches\fP"
.br
.ti -1c
.RI "char * \fBhooks\fP"
.br
.ti -1c
.RI "\fBDdHook\fP * \fBpreGCHook\fP"
.br
.ti -1c
.RI "\fBDdHook\fP * \fBpostGCHook\fP"
.br
.ti -1c
.RI "\fBDdHook\fP * \fBpreReorderingHook\fP"
.br
.ti -1c
.RI "\fBDdHook\fP * \fBpostReorderingHook\fP"
.br
.ti -1c
.RI "FILE * \fBout\fP"
.br
.ti -1c
.RI "FILE * \fBerr\fP"
.br
.ti -1c
.RI "Cudd_ErrorType \fBerrorCode\fP"
.br
.ti -1c
.RI "unsigned long \fBstartTime\fP"
.br
.ti -1c
.RI "unsigned long \fBtimeLimit\fP"
.br
.ti -1c
.RI "unsigned long \fBmemused\fP"
.br
.ti -1c
.RI "unsigned long \fBmaxmem\fP"
.br
.ti -1c
.RI "unsigned long \fBmaxmemhard\fP"
.br
.ti -1c
.RI "int \fBgarbageCollections\fP"
.br
.ti -1c
.RI "unsigned long \fBGCTime\fP"
.br
.ti -1c
.RI "unsigned long \fBreordTime\fP"
.br
.ti -1c
.RI "double \fBtotCachehits\fP"
.br
.ti -1c
.RI "double \fBtotCacheMisses\fP"
.br
.ti -1c
.RI "double \fBcachecollisions\fP"
.br
.ti -1c
.RI "double \fBcacheinserts\fP"
.br
.ti -1c
.RI "double \fBcacheLastInserts\fP"
.br
.ti -1c
.RI "double \fBcachedeletions\fP"
.br
.ti -1c
.RI "unsigned int \fBpeakLiveNodes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
