.TH "DdNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdNode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DdHalfWord \fBindex\fP"
.br
.ti -1c
.RI "DdHalfWord \fBref\fP"
.br
.ti -1c
.RI "\fBDdNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   CUDD_VALUE_TYPE \fBvalue\fP"
.br
.ti -1c
.RI "   \fBDdChildren\fP \fBkids\fP"
.br
.ti -1c
.RI "} \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
