.TH "DdSubtable" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DdSubtable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDdNode\fP ** \fBnodelist\fP"
.br
.ti -1c
.RI "int \fBshift\fP"
.br
.ti -1c
.RI "unsigned int \fBslots\fP"
.br
.ti -1c
.RI "unsigned int \fBkeys\fP"
.br
.ti -1c
.RI "unsigned int \fBmaxKeys\fP"
.br
.ti -1c
.RI "unsigned int \fBdead\fP"
.br
.ti -1c
.RI "unsigned int \fBnext\fP"
.br
.ti -1c
.RI "int \fBbindVar\fP"
.br
.ti -1c
.RI "Cudd_VariableType \fBvarType\fP"
.br
.ti -1c
.RI "int \fBpairIndex\fP"
.br
.ti -1c
.RI "int \fBvarHandled\fP"
.br
.ti -1c
.RI "Cudd_LazyGroupType \fBvarToBeGrouped\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
