.TH "EpDoubleStruct" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EpDoubleStruct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union \fBEpTypeUnion\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBexponent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
