.TH "EpTypeUnion" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EpTypeUnion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <epd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "struct \fBIeeeDoubleStruct\fP \fBbits\fP"
.br
.ti -1c
.RI "struct \fBIeeeNanStruct\fP \fBnan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct**********************************************************************
.PP
Synopsis [Extended precision double to keep very large value\&.]
.PP
Description [Extended precision double to keep very large value\&.]
.PP
SeeAlso [] 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
