.TH "hack" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hack
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CUDD_VALUE_TYPE \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBbits\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
CFile***********************************************************************
.PP
FileName [cuddTable\&.c]
.PP
PackageName [cudd]
.PP
Synopsis [Unique table management functions\&.]
.PP
Description [External procedures included in this module: 
.PD 0

.IP "\(bu" 2
Cudd_Prime() 
.IP "\(bu" 2
Cudd_Reserve() 
.PP
Internal procedures included in this module: 
.PD 0

.IP "\(bu" 2
cuddAllocNode() 
.IP "\(bu" 2
cuddInitTable() 
.IP "\(bu" 2
cuddFreeTable() 
.IP "\(bu" 2
cuddGarbageCollect() 
.IP "\(bu" 2
cuddZddGetNode() 
.IP "\(bu" 2
cuddZddGetNodeIVO() 
.IP "\(bu" 2
cuddUniqueInter() 
.IP "\(bu" 2
cuddUniqueInterIVO() 
.IP "\(bu" 2
cuddUniqueInterZdd() 
.IP "\(bu" 2
cuddUniqueConst() 
.IP "\(bu" 2
cuddRehash() 
.IP "\(bu" 2
cuddShrinkSubtable() 
.IP "\(bu" 2
cuddInsertSubtables() 
.IP "\(bu" 2
cuddDestroySubtables() 
.IP "\(bu" 2
cuddResizeTableZdd() 
.IP "\(bu" 2
cuddSlowTableGrowth() 
.PP
Static procedures included in this module: 
.PD 0

.IP "\(bu" 2
ddRehashZdd() 
.IP "\(bu" 2
ddResizeTable() 
.IP "\(bu" 2
cuddFindParent() 
.IP "\(bu" 2
cuddOrderedInsert() 
.IP "\(bu" 2
cuddOrderedThread() 
.IP "\(bu" 2
cuddRotateLeft() 
.IP "\(bu" 2
cuddRotateRight() 
.IP "\(bu" 2
cuddDoRebalance() 
.IP "\(bu" 2
cuddCheckCollisionOrdering() 
.PP
]
.PP
SeeAlso []
.PP
Author [Fabio Somenzi]
.PP
Copyright [Copyright (c) 1995-2012, Regents of the University of Colorado
.PP
All rights reserved\&.
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.PP
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.PP
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.PP
Neither the name of the University of Colorado nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission\&.
.PP
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&.] 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
