.TH "IeeeNanStruct" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IeeeNanStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <epd\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmantissa1\fP: 32"
.br
.ti -1c
.RI "unsigned int \fBmantissa0\fP: 19"
.br
.ti -1c
.RI "unsigned int \fBquiet_bit\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBexponent\fP: 11"
.br
.ti -1c
.RI "unsigned int \fBsign\fP: 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct**********************************************************************
.PP
Synopsis [IEEE double NaN struct\&.]
.PP
Description [IEEE double NaN struct\&.]
.PP
SeeAlso [] 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
