.TH "llvm::GraphTraits< Inverse< SVF::PAGNode * > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< Inverse< SVF::PAGNode * > > \- Inverse GraphTraits specializations for PAG node, it is used for inverse traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAG\&.h>\fP
.PP
Inherits GraphTraits< Inverse< SVF::GenericNode< SVF::PAGNode, SVF::PAGEdge > * > >\&.
.SH "Detailed Description"
.PP 
Inverse GraphTraits specializations for PAG node, it is used for inverse traversal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
