.TH "llvm::GraphTraits< Inverse< SVF::DCHNode * > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< Inverse< SVF::DCHNode * > > \- Inverse GraphTraits specializations for call graph node, it is used for inverse traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DCHG\&.h>\fP
.PP
Inherits GraphTraits< Inverse< SVF::GenericNode< SVF::DCHNode, SVF::DCHEdge > * > >\&.
.SH "Detailed Description"
.PP 
Inverse GraphTraits specializations for call graph node, it is used for inverse traversal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
