.TH "llvm::GraphTraits< SVF::PAG * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< SVF::PAG * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits GraphTraits< SVF::GenericGraph< SVF::PAGNode, SVF::PAGEdge > * >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSVF::PAGNode\fP * \fBNodeRef\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
