.TH "llvm::DOTGraphTraits< CHGraph * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< CHGraph * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultDOTGraphTraits\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBCHNode\fP \fBNodeType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBCHGraph\fP *)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetNodeLabel\fP (\fBCHNode\fP *node, \fBCHGraph\fP *)"
.br
.RI "Return function name;\&. "
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBCHNode\fP *node, \fBCHGraph\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBCHNode\fP *, EdgeIter EI, \fBCHGraph\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write value flow graph into dot file for debugging 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
