.TH "llvm::DOTGraphTraits< PAG * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< PAG * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultDOTGraphTraits\&.
.PP
Inherited by \fBllvm::DOTGraphTraits< ConstraintGraph * >\fP, \fBllvm::DOTGraphTraits< ICFG * >\fP, \fBllvm::DOTGraphTraits< OfflineConsG * >\fP, \fBllvm::DOTGraphTraits< SVFG * >\fP, and \fBllvm::DOTGraphTraits< VFG * >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPAGNode\fP \fBNodeType\fP"
.br
.ti -1c
.RI "typedef \fBNodeType::iterator\fP \fBChildIteratorType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBPAG\fP *graph)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetNodeLabel\fP (\fBPAGNode\fP *node, \fBPAG\fP *)"
.br
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBPAGNode\fP *node, \fBPAG\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBPAGNode\fP *, EdgeIter EI, \fBPAG\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeSourceLabel\fP (\fBPAGNode\fP *, EdgeIter EI)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write value flow graph into dot file for debugging 
.SH "Member Function Documentation"
.PP 
.SS "static std::string llvm::DOTGraphTraits< \fBPAG\fP * >::getNodeLabel (\fBPAGNode\fP * node, \fBPAG\fP *)\fC [inline]\fP, \fC [static]\fP"
Return label of a VFG node with two display mode Either you can choose to display the name of the value or the whole instruction 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
