.TH "llvm::GraphTraits< SVF::GenericGraph< NodeTy, EdgeTy > * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< SVF::GenericGraph< NodeTy, EdgeTy > * >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenericGraph\&.h>\fP
.PP
Inherits \fBllvm::GraphTraits< SVF::GenericNode< NodeTy, EdgeTy > * >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSVF::GenericGraph\fP< NodeTy, EdgeTy > \fBGenericGraphTy\fP"
.br
.ti -1c
.RI "typedef NodeTy \fBNodeType\fP"
.br
.ti -1c
.RI "typedef EdgeTy \fBEdgeType\fP"
.br
.ti -1c
.RI "typedef std::pair< SVF::NodeID, NodeType * > \fBPairTy\fP"
.br
.ti -1c
.RI "typedef std::pointer_to_unary_function< PairTy, NodeType * > \fBDerefVal\fP"
.br
.ti -1c
.RI "typedef mapped_iterator< typename \fBGenericGraphTy::iterator\fP, DerefVal > \fBnodes_iterator\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static NodeType * \fBgetEntryNode\fP (\fBGenericGraphTy\fP *pag)"
.br
.ti -1c
.RI "static nodes_iterator \fBnodes_begin\fP (\fBGenericGraphTy\fP *G)"
.br
.ti -1c
.RI "static nodes_iterator \fBnodes_end\fP (\fBGenericGraphTy\fP *G)"
.br
.ti -1c
.RI "static NodeType * \fBValdereference\fP (PairTy P)"
.br
.ti -1c
.RI "static unsigned \fBgraphSize\fP (\fBGenericGraphTy\fP *G)"
.br
.ti -1c
.RI "static unsigned \fBgetNodeID\fP (NodeType *N)"
.br
.ti -1c
.RI "static NodeType * \fBgetNode\fP (\fBGenericGraphTy\fP *G, SVF::NodeID id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class NodeTy, class EdgeTy>
.br
struct llvm::GraphTraits< SVF::GenericGraph< NodeTy, EdgeTy > * >"
GraphTraints 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
