.TH "llvm::GraphTraits< Inverse< SVF::PTACallGraphNode * > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< Inverse< SVF::PTACallGraphNode * > > \- Inverse GraphTraits specializations for call graph node, it is used for inverse traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PTACallGraph\&.h>\fP
.PP
Inherits GraphTraits< Inverse< SVF::GenericNode< SVF::PTACallGraphNode, SVF::PTACallGraphEdge > * > >\&.
.SH "Detailed Description"
.PP 
Inverse GraphTraits specializations for call graph node, it is used for inverse traversal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
