.TH "llvm::GraphTraits< Inverse< SVF::TCTNode * > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< Inverse< SVF::TCTNode * > > \- Inverse GraphTraits specializations for Value flow node, it is used for inverse traversal\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TCT\&.h>\fP
.PP
Inherits GraphTraits< Inverse< SVF::GenericNode< SVF::TCTNode, SVF::TCTEdge > * > >\&.
.SH "Detailed Description"
.PP 
Inverse GraphTraits specializations for Value flow node, it is used for inverse traversal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
