.TH "llvm::DOTGraphTraits< TCT * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< TCT * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultDOTGraphTraits\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBTCTNode\fP \fBNodeType\fP"
.br
.ti -1c
.RI "typedef \fBNodeType::iterator\fP \fBChildIteratorType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBTCT\fP *graph)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetNodeLabel\fP (\fBTCTNode\fP *node, \fBTCT\fP *graph)"
.br
.RI "Return function name;\&. "
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBTCTNode\fP *node, \fBTCT\fP *tct)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBTCTNode\fP *node, EdgeIter EI, \fBTCT\fP *csThreadTree)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write value flow graph into dot file for debugging 
.SH "Member Function Documentation"
.PP 
.SS "template<class EdgeIter > static std::string llvm::DOTGraphTraits< \fBTCT\fP * >::getEdgeAttributes (\fBTCTNode\fP * node, EdgeIter EI, \fBTCT\fP * csThreadTree)\fC [inline]\fP, \fC [static]\fP"
black edge for direct call while two functions contain indirect calls will be label with red color

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
