.TH "llvm::GraphPrinter" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphPrinter
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class GraphType > static void \fBWriteGraphToFile\fP (llvm::raw_ostream &O, const std::string &GraphName, const GraphType &GT, bool simple=false)"
.br
.ti -1c
.RI "template<class GraphType > static void \fBPrintGraph\fP (llvm::raw_ostream &O, const std::string &GraphName, const GraphType &GT)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class GraphType > static void llvm::GraphPrinter::PrintGraph (llvm::raw_ostream & O, const std::string & GraphName, const GraphType & GT)\fC [inline]\fP, \fC [static]\fP"
Print the graph to command line Define the GTraits and node iterator for printing
.SS "template<class GraphType > static void llvm::GraphPrinter::WriteGraphToFile (llvm::raw_ostream & O, const std::string & GraphName, const GraphType & GT, bool simple = \fCfalse\fP)\fC [inline]\fP, \fC [static]\fP"
Write the graph into dot file for debugging purpose 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
