.TH "llvm::GraphTraits< SVF::PTACallGraphNode * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< SVF::PTACallGraphNode * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits GraphTraits< SVF::GenericNode< SVF::PTACallGraphNode, SVF::PTACallGraphEdge > * >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
