.TH "llvm::generic_bridge_gep_type_iterator< ItTy >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::generic_bridge_gep_type_iterator< ItTy >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::iterator< std::forward_iterator_tag, Type *, ptrdiff_t >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBgeneric_bridge_gep_type_iterator\fP &x) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBgeneric_bridge_gep_type_iterator\fP &x) const"
.br
.ti -1c
.RI "Type * \fBoperator*\fP () const"
.br
.ti -1c
.RI "Type * \fBgetIndexedType\fP () const"
.br
.ti -1c
.RI "Type * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "Value * \fBgetOperand\fP () const"
.br
.ti -1c
.RI "\fBgeneric_bridge_gep_type_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBgeneric_bridge_gep_type_iterator\fP \fBoperator++\fP (int)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgeneric_bridge_gep_type_iterator\fP \fBbegin\fP (Type *Ty, ItTy It)"
.br
.ti -1c
.RI "static \fBgeneric_bridge_gep_type_iterator\fP \fBbegin\fP (Type *Ty, unsigned AddrSpace, ItTy It)"
.br
.ti -1c
.RI "static \fBgeneric_bridge_gep_type_iterator\fP \fBend\fP (ItTy It)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
