.TH "llvm::DOTGraphTraits< ICFG * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< ICFG * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBllvm::DOTGraphTraits< PAG * >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBICFGNode\fP \fBNodeType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.ti -1c
.RI "std::string \fBgetNodeLabel\fP (\fBNodeType\fP *node, \fBICFG\fP *graph)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBICFG\fP *)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetSimpleNodeLabel\fP (\fBNodeType\fP *node, \fBICFG\fP *)"
.br
.RI "Return the label of an ICFG node\&. "
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBNodeType\fP *node, \fBICFG\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBNodeType\fP *, EdgeIter EI, \fBICFG\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeSourceLabel\fP (\fBNodeType\fP *, EdgeIter EI)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
