.TH "llvm::DOTGraphTraits< PTACallGraph * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< PTACallGraph * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits DefaultDOTGraphTraits\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPTACallGraphNode\fP \fBNodeType\fP"
.br
.ti -1c
.RI "typedef NodeType::iterator \fBChildIteratorType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBPTACallGraph\fP *)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetNodeLabel\fP (\fBPTACallGraphNode\fP *node, \fBPTACallGraph\fP *)"
.br
.RI "Return function name;\&. "
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBPTACallGraphNode\fP *node, \fBPTACallGraph\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBPTACallGraphNode\fP *, EdgeIter EI, \fBPTACallGraph\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeSourceLabel\fP (\fBNodeType\fP *, EdgeIter EI)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Write value flow graph into dot file for debugging 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
