.TH "llvm::DOTGraphTraits< ConstraintGraph * >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::DOTGraphTraits< ConstraintGraph * >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBllvm::DOTGraphTraits< PAG * >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBConstraintNode\fP \fBNodeType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDOTGraphTraits\fP (bool isSimple=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgetGraphName\fP (\fBConstraintGraph\fP *)"
.br
.RI "Return name of the graph\&. "
.ti -1c
.RI "static std::string \fBgetNodeLabel\fP (\fBNodeType\fP *n, \fBConstraintGraph\fP *)"
.br
.ti -1c
.RI "static std::string \fBgetNodeAttributes\fP (\fBNodeType\fP *n, \fBConstraintGraph\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeAttributes\fP (\fBNodeType\fP *, EdgeIter EI, \fBConstraintGraph\fP *)"
.br
.ti -1c
.RI "template<class EdgeIter > static std::string \fBgetEdgeSourceLabel\fP (\fBNodeType\fP *, EdgeIter)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::string llvm::DOTGraphTraits< \fBConstraintGraph\fP * >::getNodeLabel (\fBNodeType\fP * n, \fBConstraintGraph\fP *)\fC [inline]\fP, \fC [static]\fP"
Return label of a VFG node with two display mode Either you can choose to display the name of the value or the whole instruction 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
