.TH "llvm::GraphTraits< Inverse< SVF::GenericNode< NodeTy, EdgeTy > * > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llvm::GraphTraits< Inverse< SVF::GenericNode< NodeTy, EdgeTy > * > >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenericGraph\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef NodeTy \fBNodeType\fP"
.br
.ti -1c
.RI "typedef EdgeTy \fBEdgeType\fP"
.br
.ti -1c
.RI "typedef std::pointer_to_unary_function< EdgeType *, NodeType * > \fBDerefEdge\fP"
.br
.ti -1c
.RI "typedef mapped_iterator< typename \fBSVF::GenericNode\fP< NodeTy, EdgeTy >::iterator, DerefEdge > \fBChildIteratorType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static NodeType * \fBgetEntryNode\fP (Inverse< NodeType * > G)"
.br
.ti -1c
.RI "static ChildIteratorType \fBchild_begin\fP (const NodeType *N)"
.br
.ti -1c
.RI "static ChildIteratorType \fBchild_end\fP (const NodeType *N)"
.br
.ti -1c
.RI "static NodeType * \fBedgeDereference\fP (EdgeType *edge)"
.br
.ti -1c
.RI "static unsigned \fBgetNodeID\fP (const NodeType *N)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class NodeTy, class EdgeTy>
.br
struct llvm::GraphTraits< Inverse< SVF::GenericNode< NodeTy, EdgeTy > * > >"
Inverse GraphTraits for node which is used for inverse traversal\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
