.TH "MtrNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MtrNode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MtrHalfWord \fBflags\fP"
.br
.ti -1c
.RI "MtrHalfWord \fBlow\fP"
.br
.ti -1c
.RI "MtrHalfWord \fBsize\fP"
.br
.ti -1c
.RI "MtrHalfWord \fBindex\fP"
.br
.ti -1c
.RI "struct \fBMtrNode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBMtrNode\fP * \fBchild\fP"
.br
.ti -1c
.RI "struct \fBMtrNode\fP * \fBelder\fP"
.br
.ti -1c
.RI "struct \fBMtrNode\fP * \fByounger\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
