.TH "RaceResultValidator::AccessPair" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RaceResultValidator::AccessPair
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MTAResultValidator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAccessPair\fP (const Instruction *I1, const Instruction *I2, const RC_FLAG flags)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "bool \fBisFlaged\fP (const RC_FLAG flag) const"
.br
.RI "Class member access\&. "
.ti -1c
.RI "const Instruction * \fBgetInstruction1\fP () const"
.br
.ti -1c
.RI "const Instruction * \fBgetInstruction2\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure for recording access pairs for the validation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
