.TH "st_table" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBcompare\fP )(const char *, const char *)"
.br
.ti -1c
.RI "int(* \fBhash\fP )(char *, int)"
.br
.ti -1c
.RI "int \fBnum_bins\fP"
.br
.ti -1c
.RI "int \fBnum_entries\fP"
.br
.ti -1c
.RI "int \fBmax_density\fP"
.br
.ti -1c
.RI "int \fBreorder_flag\fP"
.br
.ti -1c
.RI "double \fBgrow_factor\fP"
.br
.ti -1c
.RI "\fBst_table_entry\fP ** \fBbins\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
