.TH "st_table_entry" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
st_table_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBrecord\fP"
.br
.ti -1c
.RI "\fBst_table_entry\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
