.TH "std::hash< std::pair< T, U > >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::hash< std::pair< T, U > > \- Specialise hash for pairs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SVFBasicTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const std::pair< T, U > &p) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t \fBszudzik\fP (size_t a, size_t b)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename U>
.br
struct std::hash< std::pair< T, U > >"
Specialise hash for pairs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
