.TH "std::hash< SVF::CallSite >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::hash< SVF::CallSite > \- Specialise hash for CallSites\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BasicTypes\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const SVF::CallSite &cs) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specialise hash for CallSites\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
