.TH "SVF::SVFFunction" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFFunction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::SVFValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVFFunction\fP (const std::string &val)"
.br
.ti -1c
.RI "\fBSVFFunction\fP (Function *f)"
.br
.ti -1c
.RI "Function * \fBgetLLVMFun\fP () const"
.br
.ti -1c
.RI "bool \fBisDeclaration\fP () const"
.br
.ti -1c
.RI "bool \fBisIntrinsic\fP () const"
.br
.ti -1c
.RI "u32_t \fBarg_size\fP () const"
.br
.ti -1c
.RI "bool \fBisVarArg\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
