.TH "SVF::FieldInfo" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FieldInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LocationSet\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< NodePair > \fBElemNumStridePairVec\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldInfo\fP (u32_t idx, u32_t byteOff, const Type *ty, ElemNumStridePairVec pa)"
.br
.ti -1c
.RI "u32_t \fBgetFlattenFldIdx\fP () const"
.br
.ti -1c
.RI "u32_t \fBgetFlattenByteOffset\fP () const"
.br
.ti -1c
.RI "const Type * \fBgetFlattenElemTy\fP () const"
.br
.ti -1c
.RI "const ElemNumStridePairVec & \fBgetElemNumStridePairVect\fP () const"
.br
.ti -1c
.RI "ElemNumStridePairVec::const_iterator \fBelemStridePairBegin\fP () const"
.br
.ti -1c
.RI "ElemNumStridePairVec::const_iterator \fBelemStridePairEnd\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Field information of an aggregate object 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
