.TH "SVF::CxtThreadProc" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CxtThreadProc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CxtStmt\&.h>\fP
.PP
Inherits \fBSVF::CxtProc\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCxtThreadProc\fP (NodeID t, const CallStrCxt &c, const \fBSVFFunction\fP *f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCxtThreadProc\fP (const \fBCxtThreadProc\fP &ctm)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "virtual \fB~CxtThreadProc\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "NodeID \fBgetTid\fP () const"
.br
.RI "Return current thread id\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCxtThreadProc\fP &rhs) const"
.br
.ti -1c
.RI "\fBCxtThreadProc\fP & \fBoperator=\fP (const \fBCxtThreadProc\fP &rhs)"
.br
.RI "Overloading operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCxtThreadProc\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCxtThreadProc\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "void \fBdump\fP () const"
.br
.RI "Dump \fBCxtThreadProc\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Context-sensitive procedure <t,c,m> t represent current thread during traversing c represent current context m represent current procedure 
.SH "Member Function Documentation"
.PP 
.SS "bool SVF::CxtThreadProc::operator< (const \fBCxtThreadProc\fP & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
