.TH "SVF::PTAType" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PTAType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTAType\fP (const Type *ty)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const Type * \fBgetLLVMType\fP () const"
.br
.RI "Get the contained llvm type\&. "
.ti -1c
.RI "void \fBdump\fP () const"
.br
.RI "Dump the type\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPTAType\fP &ty) const"
.br
.RI "Operator overloading\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPTAType\fP &ty) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPTAType\fP &ty) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBPTAType\fP &ty) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
