.TH "SVF::FormalOUTSVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FormalOUTSVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::MRSVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormalOUTSVFGNode\fP (NodeID id, const \fBMemSSA::RETMU\fP *exit)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBMemSSA::RETMU\fP * \fBgetRetMU\fP () const"
.br
.RI "\fBRetMU\fP\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBFormalOUTSVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
