.TH "SVF::SVFUtil::cast_convert_val< To, From, SimpleFrom >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFUtil::cast_convert_val< To, From, SimpleFrom >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcast_retty\fP< To, From >::ret_type \fBdoit\fP (From &Val)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
