.TH "SVF::NullPtrVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::NullPtrVFGNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VFGNode\&.h>\fP
.PP
Inherits \fBSVF::VFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNullPtrVFGNode\fP (NodeID id, const \fBPAGNode\fP *n)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "bool \fBisPTANode\fP () const"
.br
.RI "Whether this node is of pointer type (used for pointer analysis)\&. "
.ti -1c
.RI "const \fBPAGNode\fP * \fBgetPAGNode\fP () const"
.br
.RI "Return corresponding \fBPAGNode\fP\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBNullPtrVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Dummy Definition for undef and null pointers 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
