.TH "SVF::UnaryOPVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::UnaryOPVFGNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VFGNode\&.h>\fP
.PP
Inherits \fBSVF::VFGNode\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Map< u32_t, const \fBPAGNode\fP * > \fBOPVers\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnaryOPVFGNode\fP (NodeID id, const \fBPAGNode\fP *r)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBPAGNode\fP * \fBgetOpVer\fP (u32_t pos) const"
.br
.RI "Operands at a UnaryNode\&. "
.ti -1c
.RI "void \fBsetOpVer\fP (u32_t pos, const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "const \fBPAGNode\fP * \fBgetRes\fP () const"
.br
.ti -1c
.RI "u32_t \fBgetOpVerNum\fP () const"
.br
.ti -1c
.RI "OPVers::const_iterator \fBopVerBegin\fP () const"
.br
.ti -1c
.RI "OPVers::const_iterator \fBopVerEnd\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBUnaryOPVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBPAGNode\fP * \fBres\fP"
.br
.ti -1c
.RI "OPVers \fBopVers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBVFGNode\fP for unary operator instructions, e\&.g\&., a = -b; 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
