.TH "SVF::DFPTData< Key, Datum, Data >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DFPTData< Key, Datum, Data >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AbstractPointsToDS\&.h>\fP
.PP
Inherits \fBSVF::PTData< Key, Datum, Data >\fP\&.
.PP
Inherited by \fBSVF::MutableDFPTData< Key, Datum, Data >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPTData\fP< Key, Datum, Data > \fBBasePTData\fP"
.br
.ti -1c
.RI "typedef \fBBasePTData::PTDataTy\fP \fBPTDataTy\fP"
.br
.ti -1c
.RI "typedef NodeID \fBLocID\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDFPTData\fP (bool reversePT=true, \fBPTDataTy\fP ty=BasePTData::DataFlow)"
.br
.RI "Constructor\&. "
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual bool \fBhasDFInSet\fP (LocID loc) const =0"
.br
.ti -1c
.RI "virtual bool \fBhasDFOutSet\fP (LocID loc) const =0"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual bool \fBhasDFOutSet\fP (LocID loc, const Key &var) const =0"
.br
.ti -1c
.RI "virtual bool \fBhasDFInSet\fP (LocID loc, const Key &var) const =0"
.br
.ti -1c
.RI "virtual const Data & \fBgetDFInPtsSet\fP (LocID loc, const Key &var)=0"
.br
.ti -1c
.RI "virtual const Data & \fBgetDFOutPtsSet\fP (LocID loc, const Key &var)=0"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "virtual bool \fBupdateDFInFromIn\fP (LocID srcLoc, const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.ti -1c
.RI "virtual bool \fBupdateAllDFInFromIn\fP (LocID srcLoc, const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.RI "Union (IN[dstLoc::dstVar], IN[srcLoc:srcVar]\&. There is no flag check, unlike the above\&. "
.ti -1c
.RI "virtual bool \fBupdateDFInFromOut\fP (LocID srcLoc, const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.RI "Union (IN[dstLoc:dstVar], OUT[srcLoc:srcVar])\&. "
.ti -1c
.RI "virtual bool \fBupdateAllDFInFromOut\fP (LocID srcLoc, const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.RI "Union (IN[dstLoc::dstVar], OUT[srcLoc:srcVar]\&. There is no flag check, unlike the above\&. "
.ti -1c
.RI "virtual bool \fBupdateDFOutFromIn\fP (LocID srcLoc, const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.RI "Union (OUT[dstLoc:dstVar], IN[srcLoc:srcVar])\&. "
.ti -1c
.RI "virtual bool \fBupdateAllDFOutFromIn\fP (LocID loc, const Key &singleton, bool strongUpdates)=0"
.br
.RI "For each variable var in IN at loc, do updateDFOutFromIn(loc, var, loc, var)\&. "
.ti -1c
.RI "virtual void \fBclearAllDFOutUpdatedVar\fP (LocID)=0"
.br
.ti -1c
.RI "virtual bool \fBupdateTLVPts\fP (LocID srcLoc, const Key &srcVar, const Key &dstVar)=0"
.br
.RI "Update points-to set of top-level pointers with IN[srcLoc:srcVar]\&. "
.ti -1c
.RI "virtual bool \fBupdateATVPts\fP (const Key &srcVar, LocID dstLoc, const Key &dstVar)=0"
.br
.RI "Update address-taken variables OUT[dstLoc:dstVar] with points-to of top-level pointers\&. "
.in -1c
.in -1c
.SS "Static Public Member Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBDFPTData\fP< Key, Datum, Data > *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPTData\fP< Key, Datum, Data > *ptd)"
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Key, typename Datum, typename Data>
.br
class SVF::DFPTData< Key, Datum, Data >"
Data-flow points-to data structure for flow-sensitive analysis as defined by Hardekopf and Lin (CGO 11)\&. Points-to information is maintained at each program point (statement)\&. For address-taken variables, every program point has two sets: IN and OUT points-to sets\&. For top-level variables, points-to sets are maintained flow-insensitively via getPts(var)\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key , typename Datum , typename Data > static bool \fBSVF::DFPTData\fP< Key, Datum, Data >::classof (const \fBDFPTData\fP< Key, Datum, Data > *)\fC [inline]\fP, \fC [static]\fP"
Methods to support type inquiry through isa, cast, and dyn_cast: 
.SS "template<typename Key , typename Datum , typename Data > virtual bool \fBSVF::DFPTData\fP< Key, Datum, Data >::hasDFInSet (LocID loc) const\fC [pure virtual]\fP"
Determine whether the DF IN/OUT sets have points-to sets\&. 
.PP
Implemented in \fBSVF::MutableDFPTData< Key, Datum, Data >\fP\&.
.SS "template<typename Key , typename Datum , typename Data > virtual bool \fBSVF::DFPTData\fP< Key, Datum, Data >::hasDFOutSet (LocID loc, const Key & var) const\fC [pure virtual]\fP"
Access points-to set from data-flow IN/OUT set\&. 
.PP
Implemented in \fBSVF::MutableDFPTData< Key, Datum, Data >\fP\&.
.SS "template<typename Key , typename Datum , typename Data > virtual bool \fBSVF::DFPTData\fP< Key, Datum, Data >::updateDFInFromIn (LocID srcLoc, const Key & srcVar, LocID dstLoc, const Key & dstVar)\fC [pure virtual]\fP"
Update points-to for IN/OUT set IN[loc:var] represents the points-to of variable var in the IN set of location loc\&. union(ptsDst, ptsSrc) represents ptsDst = ptsDst U ptsSrc\&.
.PP
Union (IN[dstLoc:dstVar], IN[srcLoc:srcVar])\&. 
.PP
Implemented in \fBSVF::IncMutableDFPTData< Key, Datum, Data >\fP, and \fBSVF::MutableDFPTData< Key, Datum, Data >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
