.TH "SVF::DoubleFreeChecker" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DoubleFreeChecker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DoubleFreeChecker\&.h>\fP
.PP
Inherits \fBSVF::LeakChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDoubleFreeChecker\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~DoubleFreeChecker\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual bool \fBrunOnModule\fP (\fBSVFModule\fP *module)"
.br
.RI "We start from here\&. "
.ti -1c
.RI "void \fBreportBug\fP (\fBProgSlice\fP *slice)"
.br
.RI "Report file/close bugs\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Double free checker to check deallocations of memory 
.SH "Member Function Documentation"
.PP 
.SS "virtual bool SVF::DoubleFreeChecker::runOnModule (\fBSVFModule\fP * module)\fC [inline]\fP, \fC [virtual]\fP"

.PP
We start from here\&. start analysis
.PP
Reimplemented from \fBSVF::LeakChecker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
