.TH "SVF::RetMU< Cond >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::RetMU< Cond >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSSAMuChi\&.h>\fP
.PP
Inherits \fBSVF::MSSAMU< Cond >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRetMU\fP (const \fBSVFFunction\fP *f, const \fBMemRegion\fP *m, Cond c=PathCondAllocator::trueCond())"
.br
.RI "Constructor/Destructor for MU\&. "
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetFunction\fP () const"
.br
.RI "Return function\&. "
.ti -1c
.RI "virtual void \fBdump\fP ()"
.br
.RI "Print MU\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBRetMU\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMSSAMU\fP< Cond > *mu)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class Cond>
.br
class SVF::RetMU< Cond >"
\fBRetMU\fP is annotated at function return, representing memory objects returns to callers 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
