.TH "SVF::CallGraphBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CallGraphBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSVF::ThreadCallGraphBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallGraphBuilder\fP (\fBPTACallGraph\fP *cg, \fBICFG\fP *i)"
.br
.ti -1c
.RI "\fBPTACallGraph\fP * \fBbuildCallGraph\fP (\fBSVFModule\fP *svfModule)"
.br
.RI "Build normal callgraph\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPTACallGraph\fP * \fBcallgraph\fP"
.br
.ti -1c
.RI "\fBICFG\fP * \fBicfg\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBPTACallGraph\fP * CallGraphBuilder::buildCallGraph (\fBSVFModule\fP * svfModule)"

.PP
Build normal callgraph\&. create nodes
.PP
create edges

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
