.TH "SVF::WPASCCSolver< GraphType >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::WPASCCSolver< GraphType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WPAFSSolver\&.h>\fP
.PP
Inherits \fBSVF::WPAFSSolver< GraphType >\fP\&.
.PP
Inherited by \fBSVF::WPAMinimumSolver< GraphType >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBWPASolver\fP< GraphType >::GTraits \fBGTraits\fP"
.br
.ti -1c
.RI "typedef \fBWPASolver\fP< GraphType >::GNODE \fBGNODE\fP"
.br
.ti -1c
.RI "typedef \fBWPASolver\fP< GraphType >::child_iterator \fBchild_iterator\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsolve\fP ()"
.br
.RI "Constraint Solving\&. "
.ti -1c
.RI "virtual void \fBpropagate\fP (GNODE *v)"
.br
.RI "Propagation for the solving, to be implemented in the child class\&. "
.ti -1c
.RI "virtual void \fBaddNodeIntoWorkList\fP (NodeID node)"
.br
.ti -1c
.RI "bool \fBisInCurrentSCC\fP (NodeID node)"
.br
.ti -1c
.RI "void \fBsetCurrentSCC\fP (NodeID id)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NodeID \fBcurSCCID\fP"
.br
.RI "index of current SCC\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class GraphType>
.br
class SVF::WPASCCSolver< GraphType >"
Solver based on SCC cycles\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class GraphType > virtual void \fBSVF::WPASCCSolver\fP< GraphType >::solve ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Constraint Solving\&. All nodes will be solved afterwards, so the worklist can be cleared before each solve iteration\&.
.PP
Reimplemented from \fBSVF::WPASolver< GraphType >\fP\&.
.PP
Reimplemented in \fBSVF::WPAMinimumSolver< GraphType >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
