.TH "SVF::CSC" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CSC
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSC\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Map< NodeID, NodeID > \fBIdToIdMap\fP"
.br
.ti -1c
.RI "typedef \fBFILOWorkList\fP< NodeID > \fBWorkStack\fP"
.br
.ti -1c
.RI "typedef IdToIdMap::iterator \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSC\fP (\fBConstraintGraph\fP *g, \fBCGSCC\fP *c)"
.br
.ti -1c
.RI "void \fBfind\fP (NodeStack &candidates)"
.br
.ti -1c
.RI "void \fBvisit\fP (NodeID nodeId, Size_t _w)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBisVisited\fP (NodeID nId)"
.br
.ti -1c
.RI "void \fBsetVisited\fP (NodeID nId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
class \fBCSC\fP: cycle stride calculation 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
