.TH "SVF::ThreadCallGraphBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ThreadCallGraphBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::CallGraphBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadCallGraphBuilder\fP (\fBThreadCallGraph\fP *cg, \fBICFG\fP *i)"
.br
.ti -1c
.RI "\fBPTACallGraph\fP * \fBbuildThreadCallGraph\fP (\fBSVFModule\fP *svfModule)"
.br
.RI "Build thread-aware callgraph\&. "
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
