.TH "SVF::DCHEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DCHEdge
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericEdge< DCHNode >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBINHERITANCE\fP, \fBINSTANCE\fP, \fBFIRST_FIELD\fP, \fBSTD_DEF\fP }"
.br
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBDCHNode\fP, \fBDCHEdge\fP >::GEdgeSetTy \fBDCHEdgeSetTy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDCHEdge\fP (\fBDCHNode\fP *src, \fBDCHNode\fP *dst, \fBGEdgeFlag\fP k=0)"
.br
.ti -1c
.RI "unsigned int \fBgetOffset\fP (void) const"
.br
.ti -1c
.RI "void \fBsetOffset\fP (unsigned int offset)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
