.TH "SVF::GenericEdge< NodeTy >::equalGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::GenericEdge< NodeTy >::equalGEdge \- Add the hash function for std::set (we also can overload operator< to implement this)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenericGraph\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBGenericEdge\fP< \fBNodeType\fP > *lhs, const \fBGenericEdge\fP< \fBNodeType\fP > *rhs) const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class NodeTy>
.br
struct SVF::GenericEdge< NodeTy >::equalGEdge"
Add the hash function for std::set (we also can overload operator< to implement this) 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
