.TH "SVF::List< Data >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::List< Data >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorkList\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBfind\fP (Data data) const"
.br
.ti -1c
.RI "void \fBpush\fP (Data data)"
.br
.ti -1c
.RI "Data \fBpop\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Data>
.br
class SVF::List< Data >"
Worklist with 'first come first go' order\&. New nodes pushed at back and popped from front\&. Elements in the list are unique as they're recorded by Set\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class Data > Data \fBSVF::List\fP< Data >::pop ()\fC [inline]\fP"
get node from list head
.PP
change list head to the next node
.PP
the last node is popped\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
