.TH "SVF::PTACallGraphEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PTACallGraphEdge
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericEdge< NodeTy >\fP\&.
.PP
Inherited by \fBSVF::HareParForEdge\fP, \fBSVF::ThreadForkEdge\fP, and \fBSVF::ThreadJoinEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCEDGEK\fP { \fBCallRetEdge\fP, \fBTDForkEdge\fP, \fBTDJoinEdge\fP, \fBHareParForEdge\fP }"
.br
.ti -1c
.RI "typedef Set< const \fBCallBlockNode\fP * > \fBCallInstSet\fP"
.br
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBPTACallGraphNode\fP, \fBPTACallGraphEdge\fP >::GEdgeSetTy \fBCallGraphEdgeSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTACallGraphEdge\fP (\fBPTACallGraphNode\fP *s, \fBPTACallGraphNode\fP *d, CEDGEK kind, CallSiteID cs)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~PTACallGraphEdge\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "CallSiteID \fBgetCallSiteID\fP () const"
.br
.RI "Get direct and indirect calls\&. "
.ti -1c
.RI "bool \fBisDirectCallEdge\fP () const"
.br
.ti -1c
.RI "bool \fBisIndirectCallEdge\fP () const"
.br
.ti -1c
.RI "CallInstSet & \fBgetDirectCalls\fP ()"
.br
.ti -1c
.RI "CallInstSet & \fBgetIndirectCalls\fP ()"
.br
.ti -1c
.RI "const CallInstSet & \fBgetDirectCalls\fP () const"
.br
.ti -1c
.RI "const CallInstSet & \fBgetIndirectCalls\fP () const"
.br
.ti -1c
.RI "void \fBaddDirectCallSite\fP (const \fBCallBlockNode\fP *call)"
.br
.RI "Add direct and indirect callsite\&. "
.ti -1c
.RI "void \fBaddInDirectCallSite\fP (const \fBCallBlockNode\fP *call)"
.br
.ti -1c
.RI "CallInstSet::const_iterator \fBdirectCallsBegin\fP () const"
.br
.RI "Iterators for direct and indirect callsites\&. "
.ti -1c
.RI "CallInstSet::const_iterator \fBdirectCallsEnd\fP () const"
.br
.ti -1c
.RI "CallInstSet::const_iterator \fBindirectCallsBegin\fP () const"
.br
.ti -1c
.RI "CallInstSet::const_iterator \fBindirectCallsEnd\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGEdgeFlag\fP \fBmakeEdgeFlagWithInvokeID\fP (GEdgeKind k, CallSiteID cs)"
.br
.RI "Compute the unique edgeFlag value from edge kind and CallSiteID\&. "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPTACallGraphEdge\fP *)"
.br
.RI "ClassOf\&. "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericCallGraphEdgeTy\fP *edge)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBraw_ostream\fP & \fBoperator<<\fP (\fBraw_ostream\fP &o, const \fBPTACallGraphEdge\fP &edge)"
.br
.RI "Overloading operator << for dumping \fBICFG\fP node ID\&. "
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
