.TH "SVF::StorePE" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::StorePE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAGEdge\&.h>\fP
.PP
Inherits \fBSVF::PAGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStorePE\fP (\fBPAGNode\fP *s, \fBPAGNode\fP *d, const \fBIntraBlockNode\fP *st)"
.br
.RI "constructor "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBStorePE\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Store edge 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
