.TH "SVF::VersionedPTData< Key, Datum, Data, VersionedKey >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::VersionedPTData< Key, Datum, Data, VersionedKey >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AbstractPointsToDS\&.h>\fP
.PP
Inherits \fBSVF::PTData< Key, Datum, Data >\fP\&.
.PP
Inherited by \fBSVF::MutableVersionedPTData< Key, Datum, Data, VersionedKey >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPTData\fP< Key, Datum, Data > \fBBasePTData\fP"
.br
.ti -1c
.RI "typedef \fBBasePTData::PTDataTy\fP \fBPTDataTy\fP"
.br
.ti -1c
.RI "typedef BasePTData::KeySet \fBKeySet\fP"
.br
.ti -1c
.RI "typedef Set< VersionedKey > \fBVersionedKeySet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersionedPTData\fP (bool reversePT=true, \fBPTDataTy\fP ty=PTDataTy::Versioned)"
.br
.ti -1c
.RI "virtual const Data & \fBgetPts\fP (const VersionedKey &vk)=0"
.br
.ti -1c
.RI "virtual const VersionedKeySet & \fBgetVersionedKeyRevPts\fP (const Datum &datum)=0"
.br
.ti -1c
.RI "virtual bool \fBaddPts\fP (const VersionedKey &vk, const Datum &element)=0"
.br
.ti -1c
.RI "virtual bool \fBunionPts\fP (const VersionedKey &dstVar, const VersionedKey &srcVar)=0"
.br
.ti -1c
.RI "virtual bool \fBunionPts\fP (const VersionedKey &dstVar, const Key &srcVar)=0"
.br
.ti -1c
.RI "virtual bool \fBunionPts\fP (const Key &dstVar, const VersionedKey &srcVar)=0"
.br
.ti -1c
.RI "virtual bool \fBunionPts\fP (const VersionedKey &dstVar, const Data &srcData)=0"
.br
.ti -1c
.RI "virtual void \fBclearPts\fP (const VersionedKey &vk, const Datum &element)=0"
.br
.ti -1c
.RI "virtual void \fBclearFullPts\fP (const VersionedKey &vk)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVersionedPTData\fP< Key, Datum, Data, VersionedKey > *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPTData\fP< Key, Datum, Data > *ptd)"
.br
.in -1c
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename Key, typename Datum, typename Data, typename VersionedKey>
.br
class SVF::VersionedPTData< Key, Datum, Data, VersionedKey >"
\fBPTData\fP with normal keys and versioned keys\&. Replicates the \fBPTData\fP interface for versioned keys too\&. Intended to be used for versioned flow-sensitive PTA--hence the name--but can be used anywhere where there are two types of keys at play\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key , typename Datum , typename Data , typename VersionedKey > static bool \fBSVF::VersionedPTData\fP< Key, Datum, Data, VersionedKey >::classof (const \fBVersionedPTData\fP< Key, Datum, Data, VersionedKey > *)\fC [inline]\fP, \fC [static]\fP"
Methods to support type inquiry through isa, cast, and dyn_cast: 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
