.TH "SVF::SaberSVFGBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SaberSVFGBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::SVFGBuilder\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Set< const \fBSVFGNode\fP * > \fBSVFGNodeSet\fP"
.br
.ti -1c
.RI "typedef Map< NodeID, NodeBS > \fBNodeToPTSSMap\fP"
.br
.ti -1c
.RI "typedef \fBFIFOWorkList\fP< NodeID > \fBWorkList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaberSVFGBuilder\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~SaberSVFGBuilder\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "bool \fBisGlobalSVFGNode\fP (const \fBSVFGNode\fP *node) const"
.br
.ti -1c
.RI "void \fBaddActualParmVFGNode\fP (const \fBPAGNode\fP *pagNode, const \fBCallBlockNode\fP *cs)"
.br
.RI "Add \fBActualParmVFGNode\fP\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbuildSVFG\fP ()"
.br
.RI "Re-write create \fBSVFG\fP method\&. "
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
