.TH "SVF::TCTNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::TCTNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericNode< NodeTy, EdgeTy >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTCTNode\fP (NodeID i, const \fBCxtThread\fP &cctx)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBdump\fP ()"
.br
.ti -1c
.RI "const \fBCxtThread\fP & \fBgetCxtThread\fP () const"
.br
.RI "Get \fBCxtThread\fP\&. "
.ti -1c
.RI "bool \fBisInloop\fP () const"
.br
.RI "inloop, incycle attributes "
.ti -1c
.RI "bool \fBisIncycle\fP () const"
.br
.ti -1c
.RI "void \fBsetMultiforked\fP (bool value)"
.br
.ti -1c
.RI "bool \fBisMultiforked\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
