.TH "SVF::MRVer" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MRVer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSSAMuChi\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBMSSADEF\fP \fBMSSADef\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMRVer\fP (const \fBMemRegion\fP *m, MRVERSION v, \fBMSSADef\fP *d)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBMemRegion\fP * \fBgetMR\fP () const"
.br
.RI "Return the memory region\&. "
.ti -1c
.RI "MRVERSION \fBgetSSAVersion\fP () const"
.br
.RI "Return SSA version\&. "
.ti -1c
.RI "\fBMSSADef\fP * \fBgetDef\fP () const"
.br
.RI "Get MSSADef\&. "
.in -1c
.SH "Detailed Description"
.PP 
Memory SSA Variable (in the form of SSA versions of each memory region ) 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
