.TH "SVF::MemRegion::equalMemRegion" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MemRegion::equalMemRegion
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemRegion\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBMemRegion\fP *lhs, const \fBMemRegion\fP *rhs) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
add the hash function here to sort elements and remove and remove duplicated element in the set (binary tree comparision) 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
