.TH "SVF::InterBlockNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::InterBlockNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ICFGNode\fP\&.
.PP
Inherited by \fBSVF::CallBlockNode\fP, \fBSVF::FunEntryBlockNode\fP, \fBSVF::FunExitBlockNode\fP, and \fBSVF::RetBlockNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterBlockNode\fP (NodeID id, \fBICFGNodeK\fP k)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBInterBlockNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBICFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericICFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
