.TH "SVF::AndersenSFR" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenSFR
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AndersenSFR\&.h>\fP
.PP
Inherits \fBSVF::AndersenSCD\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Map< NodeID, NodeBS > \fBNodeStrides\fP"
.br
.ti -1c
.RI "typedef Map< NodeID, NodeSet > \fBFieldReps\fP"
.br
.ti -1c
.RI "typedef Map< NodeID, pair< NodeID, NodeSet > > \fBSFRTrait\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenSFR\fP (\fBPAG\fP *_pag, \fBPTATY\fP type=\fBAndersenSFR_WPA\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAndersenSFR\fP * \fBcreateAndersenSFR\fP (\fBPAG\fP *_pag)"
.br
.RI "Create an singleton instance directly instead of invoking llvm pass manager\&. "
.ti -1c
.RI "static void \fBreleaseAndersenSFR\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.RI "Initialize analysis\&. "
.ti -1c
.RI "void \fBPWCDetect\fP ()"
.br
.ti -1c
.RI "void \fBfieldExpand\fP (NodeSet &initials, Size_t offset, NodeBS &strides, PointsTo &expandPts)"
.br
.ti -1c
.RI "bool \fBprocessGepPts\fP (PointsTo &pts, const \fBGepCGEdge\fP *edge)"
.br
.ti -1c
.RI "bool \fBmergeSrcToTgt\fP (NodeID nodeId, NodeID newRepId)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Selective Cycle Detection with Stride-based Field Representation 
.SH "Member Function Documentation"
.PP 
.SS "void AndersenSFR::initialize ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Initialize analysis\&. Initilize analysis Initialize worklist
.PP
Reimplemented from \fBSVF::Andersen\fP\&.
.SS "bool AndersenSFR::mergeSrcToTgt (NodeID nodeId, NodeID newRepId)\fC [protected]\fP, \fC [virtual]\fP"
merge nodeId to newRepId\&. Return true if the newRepId is a PWC node union pts of node to rep
.PP
move the edges from node to rep, and remove the node
.PP
set rep and sub relations
.PP
Reimplemented from \fBSVF::Andersen\fP\&.
.SS "bool AndersenSFR::processGepPts (PointsTo & pts, const \fBGepCGEdge\fP * edge)\fC [protected]\fP"
Propagate point-to set via a gep edge, using SFR 
.SS "void AndersenSFR::PWCDetect ()\fC [protected]\fP, \fC [virtual]\fP"
Call the PWC stride calculation method of class \fBCSC\fP\&. 
.PP
Reimplemented from \fBSVF::AndersenSCD\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
