.TH "SVF::PTACallGraphNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PTACallGraphNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericNode< NodeTy, EdgeTy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef PTACallGraphEdge::CallGraphEdgeSet \fBCallGraphEdgeSet\fP"
.br
.ti -1c
.RI "typedef PTACallGraphEdge::CallGraphEdgeSet::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef PTACallGraphEdge::CallGraphEdgeSet::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTACallGraphNode\fP (NodeID i, const \fBSVFFunction\fP *f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetFunction\fP () const"
.br
.RI "Get function of this call node\&. "
.ti -1c
.RI "bool \fBisReachableFromProgEntry\fP () const"
.br
.RI "Return TRUE if this function can be reached from main\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBraw_ostream\fP & \fBoperator<<\fP (\fBraw_ostream\fP &o, const \fBPTACallGraphNode\fP &node)"
.br
.RI "Overloading operator << for dumping \fBICFG\fP node ID\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
