.TH "SVF::FILOWorkList< Data >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FILOWorkList< Data >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WorkList\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBfind\fP (Data data) const"
.br
.ti -1c
.RI "bool \fBpush\fP (Data data)"
.br
.ti -1c
.RI "Data \fBpop\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Data>
.br
class SVF::FILOWorkList< Data >"
Worlist with 'first in last out' order\&. New nodes will be pushed at back and popped from back\&. Elements in the list are unique as they're recorded by Set\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<class Data > void \fBSVF::FILOWorkList\fP< Data >::clear ()\fC [inline]\fP"
Clear all the data 
.SS "template<class Data > Data \fBSVF::FILOWorkList\fP< Data >::pop ()\fC [inline]\fP"
Pop a data from the END of work list\&. 
.SS "template<class Data > bool \fBSVF::FILOWorkList\fP< Data >::push (Data data)\fC [inline]\fP"
Push a data into the work list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
