.TH "SVF::DistinctMRG" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DistinctMRG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemPartition\&.h>\fP
.PP
Inherits \fBSVF::MRGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDistinctMRG\fP (\fBBVDataPTAImpl\fP *p, bool ptrOnly)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpartitionMRs\fP ()"
.br
.RI "Partition regions\&. "
.ti -1c
.RI "virtual void \fBgetMRsForLoad\fP (\fBMRSet\fP &aliasMRs, const PointsTo &cpts, const \fBSVFFunction\fP *fun)"
.br
.RI "Get memory region at a load\&. "
.ti -1c
.RI "virtual void \fBgetMRsForCallSiteRef\fP (\fBMRSet\fP &aliasMRs, const PointsTo &cpts, const \fBSVFFunction\fP *fun)"
.br
.RI "Get memory regions to be inserted at a load statement\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Distinct memory region generator\&. 
.SH "Member Function Documentation"
.PP 
.SS "void DistinctMRG::getMRsForCallSiteRef (\fBMRSet\fP & aliasMRs, const PointsTo & cpts, const \fBSVFFunction\fP * fun)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Get memory regions to be inserted at a load statement\&. Get memory regions to be inserted at a load statement\&. Just process as \fBgetMRsForLoad()\fP\&. 
.PP
Reimplemented from \fBSVF::MRGenerator\fP\&.
.SS "void DistinctMRG::getMRsForLoad (\fBMRSet\fP & mrs, const PointsTo & pts, const \fBSVFFunction\fP * fun)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Get memory region at a load\&. Get memory regions to be inserted at a load statement\&. 
.PP
\fBParameters\fP
.RS 4
\fIcpts\fP The conditional points-to set of load statement\&. 
.br
\fIfun\fP The function being analyzed\&. 
.br
\fImrs\fP Memory region set contains all possible target memory regions\&. 
.RE
.PP
Get memory regions for each points-to element in cpts\&.
.PP
Reimplemented from \fBSVF::MRGenerator\fP\&.
.SS "void DistinctMRG::partitionMRs ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Partition regions\&. Create distinct memory regions\&. Collect all points-to target in a function scope\&.
.PP
Reimplemented from \fBSVF::MRGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
