.TH "SVF::ICFGPrinter" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ICFGPrinter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ICFG\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintICFGToJson\fP (const std::string &filename)"
.br
.ti -1c
.RI "std::string \fBgetPAGNodeKindValue\fP (int kind)"
.br
.ti -1c
.RI "std::string \fBgetPAGEdgeKindValue\fP (int kind)"
.br
.ti -1c
.RI "std::string \fBgetICFGKind\fP (const int kind)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
