.TH "SVF::FunptrDDAClient" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FunptrDDAClient
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DDAClient\&.h>\fP
.PP
Inherits \fBSVF::DDAClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunptrDDAClient\fP (\fBSVFModule\fP *\fBmodule\fP)"
.br
.ti -1c
.RI "virtual OrderedNodeSet & \fBcollectCandidateQueries\fP (\fBPAG\fP *p)"
.br
.RI "Only collect function pointers as query candidates\&. "
.ti -1c
.RI "virtual void \fBperformStat\fP (\fBPointerAnalysis\fP *pta)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
DDA client with function pointers as query candidates\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
