.TH "SVF::CHGraph" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CHGraph
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::CommonCHGraph\fP, and \fBSVF::GenericGraph< NodeTy, EdgeTy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBRELATIONTYPE\fP { \fBCONSTRUCTOR\fP = 0x1, \fBDESTRUCTOR\fP = 0x2 }"
.br
.ti -1c
.RI "typedef Set< const \fBCHNode\fP * > \fBCHNodeSetTy\fP"
.br
.ti -1c
.RI "typedef \fBFIFOWorkList\fP< const \fBCHNode\fP * > \fBWorkList\fP"
.br
.ti -1c
.RI "typedef Map< std::string, CHNodeSetTy > \fBNameToCHNodesMap\fP"
.br
.ti -1c
.RI "typedef Map< CallSite, CHNodeSetTy > \fBCallSiteToCHNodesMap\fP"
.br
.ti -1c
.RI "typedef Map< CallSite, VTableSet > \fBCallSiteToVTableSetMap\fP"
.br
.ti -1c
.RI "typedef Map< CallSite, VFunSet > \fBCallSiteToVFunSetMap\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHGraph\fP (\fBSVFModule\fP *svfModule)"
.br
.ti -1c
.RI "void \fBbuildCHG\fP ()"
.br
.ti -1c
.RI "void \fBbuildInternalMaps\fP ()"
.br
.ti -1c
.RI "void \fBbuildCHGNodes\fP (const GlobalValue *V)"
.br
.ti -1c
.RI "void \fBbuildCHGNodes\fP (const \fBSVFFunction\fP *F)"
.br
.ti -1c
.RI "void \fBbuildCHGEdges\fP (const \fBSVFFunction\fP *F)"
.br
.ti -1c
.RI "void \fBconnectInheritEdgeViaCall\fP (const \fBSVFFunction\fP *caller, CallSite cs)"
.br
.ti -1c
.RI "void \fBconnectInheritEdgeViaStore\fP (const \fBSVFFunction\fP *caller, const StoreInst *store)"
.br
.ti -1c
.RI "void \fBaddEdge\fP (const std::string className, const std::string baseClassName, CHEdge::CHEDGETYPE edgeType)"
.br
.ti -1c
.RI "\fBCHNode\fP * \fBgetNode\fP (const std::string name) const"
.br
.ti -1c
.RI "\fBCHNode\fP * \fBcreateNode\fP (const std::string name)"
.br
.ti -1c
.RI "void \fBbuildClassNameToAncestorsDescendantsMap\fP ()"
.br
.ti -1c
.RI "void \fBbuildVirtualFunctionToIDMap\fP ()"
.br
.ti -1c
.RI "void \fBbuildCSToCHAVtblsAndVfnsMap\fP ()"
.br
.ti -1c
.RI "void \fBreadInheritanceMetadataFromModule\fP (const Module &M)"
.br
.ti -1c
.RI "void \fBanalyzeVTables\fP (const Module &M)"
.br
.ti -1c
.RI "const CHGraph::CHNodeSetTy & \fBgetInstancesAndDescendants\fP (const std::string className)"
.br
.ti -1c
.RI "const CHNodeSetTy & \fBgetCSClasses\fP (CallSite cs)"
.br
.ti -1c
.RI "void \fBgetVFnsFromVtbls\fP (CallSite cs, const VTableSet &vtbls, VFunSet &virtualFunctions) override"
.br
.ti -1c
.RI "void \fBdump\fP (const std::string &filename)"
.br
.ti -1c
.RI "void \fBprintCH\fP ()"
.br
.ti -1c
.RI "s32_t \fBgetVirtualFunctionID\fP (const \fBSVFFunction\fP *vfn) const"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetVirtualFunctionBasedonID\fP (s32_t id) const"
.br
.ti -1c
.RI "void \fBaddInstances\fP (const std::string templateName, \fBCHNode\fP *node)"
.br
.ti -1c
.RI "const CHNodeSetTy & \fBgetDescendants\fP (const std::string className)"
.br
.ti -1c
.RI "const CHNodeSetTy & \fBgetInstances\fP (const std::string className)"
.br
.ti -1c
.RI "bool \fBcsHasVtblsBasedonCHA\fP (CallSite cs) override"
.br
.ti -1c
.RI "bool \fBcsHasVFnsBasedonCHA\fP (CallSite cs) override"
.br
.ti -1c
.RI "const VTableSet & \fBgetCSVtblsBasedonCHA\fP (CallSite cs) override"
.br
.ti -1c
.RI "const VFunSet & \fBgetCSVFsBasedonCHA\fP (CallSite cs) override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCommonCHGraph\fP *chg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void CHGraph::dump (const std::string & filename)"
Dump call graph into dot file 
.SS "void CHGraph::getVFnsFromVtbls (CallSite cs, const VTableSet & vtbls, VFunSet & virtualFunctions)\fC [override]\fP, \fC [virtual]\fP"
get target virtual functions
.PP
get the function name of the virtual callsite
.PP
Implements \fBSVF::CommonCHGraph\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
