.TH "SVF::TCTEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::TCTEdge
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericEdge< NodeTy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCEDGEK\fP { \fBThreadCreateEdge\fP }"
.br
.ti -1c
.RI "typedef Set< const Instruction * > \fBCallInstSet\fP"
.br
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBTCTNode\fP, \fBTCTEdge\fP >::GEdgeSetTy \fBThreadCreateEdgeSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTCTEdge\fP (\fBTCTNode\fP *s, \fBTCTNode\fP *d, CEDGEK kind)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~TCTEdge\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBTCTEdge\fP *edge)"
.br
.RI "Classof\&. "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericTCTEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
