.TH "SVF::PTACFInfoBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PTACFInfoBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Map< const Function *, DominatorTree * > \fBFunToDTMap\fP"
.br
.RI "map a function to its dominator tree "
.ti -1c
.RI "typedef Map< const Function *, PostDominatorTree * > \fBFunToPostDTMap\fP"
.br
.RI "map a function to its post dominator tree "
.ti -1c
.RI "typedef Map< const Function *, LoopInfo * > \fBFunToLoopInfoMap\fP"
.br
.RI "map a function to its loop info "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTACFInfoBuilder\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "LoopInfo * \fBgetLoopInfo\fP (const Function *f)"
.br
.RI "Get loop info of a function\&. "
.ti -1c
.RI "PostDominatorTree * \fBgetPostDT\fP (const Function *f)"
.br
.RI "Get post dominator tree of a function\&. "
.ti -1c
.RI "DominatorTree * \fBgetDT\fP (const Function *f)"
.br
.RI "Get dominator tree of a function\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
