.TH "SVF::DDAStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DDAStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DDAStat\&.h>\fP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDDAStat\fP (\fBFlowDDA\fP *pta)"
.br
.ti -1c
.RI "\fBDDAStat\fP (\fBContextDDA\fP *pta)"
.br
.ti -1c
.RI "void \fBperformStatPerQuery\fP (NodeID ptr)"
.br
.ti -1c
.RI "void \fBperformStat\fP ()"
.br
.ti -1c
.RI "void \fBprintStat\fP ()"
.br
.ti -1c
.RI "void \fBprintStatPerQuery\fP (NodeID ptr, const PointsTo &pts)"
.br
.ti -1c
.RI "void \fBgetNumOfOOBQuery\fP ()"
.br
.ti -1c
.RI "void \fBsetMemUsageBefore\fP (u32_t vmrss, u32_t vmsize)"
.br
.ti -1c
.RI "void \fBsetMemUsageAfter\fP (u32_t vmrss, u32_t vmsize)"
.br
.ti -1c
.RI "\fBSVFG\fP * \fBgetSVFG\fP () const"
.br
.ti -1c
.RI "\fBPointerAnalysis\fP * \fBgetPTA\fP () const"
.br
.ti -1c
.RI "NodeBS & \fBgetStrongUpdateStores\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u32_t \fB_NumOfDPM\fP"
.br
.ti -1c
.RI "u32_t \fB_NumOfStrongUpdates\fP"
.br
.ti -1c
.RI "u32_t \fB_NumOfMustAliases\fP"
.br
.ti -1c
.RI "u32_t \fB_NumOfInfeasiblePath\fP"
.br
.ti -1c
.RI "u64_t \fB_NumOfStep\fP"
.br
.ti -1c
.RI "u64_t \fB_NumOfStepInCycle\fP"
.br
.ti -1c
.RI "double \fB_AnaTimePerQuery\fP"
.br
.ti -1c
.RI "double \fB_AnaTimeCyclePerQuery\fP"
.br
.ti -1c
.RI "double \fB_TotalTimeOfQueries\fP"
.br
.ti -1c
.RI "double \fB_TotalTimeOfBKCondition\fP"
.br
.ti -1c
.RI "NodeBS \fB_StrongUpdateStores\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Statistics of demand-driven analysis 
.SH "Member Function Documentation"
.PP 
.SS "void DDAStat::performStatPerQuery (NodeID ptr)\fC [virtual]\fP"
reset numbers for next query
.PP
Reimplemented from \fBSVF::PTAStat\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
