.TH "SVF::SVFGStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFGStat
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Set< const \fBSVFGNode\fP * > \fBSVFGNodeSet\fP"
.br
.ti -1c
.RI "typedef OrderedSet< const \fBSVFGEdge\fP * > \fBSVFGEdgeSet\fP"
.br
.ti -1c
.RI "typedef \fBSCCDetection\fP< \fBSVFG\fP * > \fBSVFGSCC\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVFGStat\fP (\fBSVFG\fP *g)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP ()"
.br
.ti -1c
.RI "virtual void \fBprintStat\fP ()"
.br
.ti -1c
.RI "virtual void \fBperformSCCStat\fP (SVFGEdgeSet insensitiveCalRetEdges)"
.br
.ti -1c
.RI "void \fBdirVFEdgeStart\fP ()"
.br
.ti -1c
.RI "void \fBdirVFEdgeEnd\fP ()"
.br
.ti -1c
.RI "void \fBindVFEdgeStart\fP ()"
.br
.ti -1c
.RI "void \fBindVFEdgeEnd\fP ()"
.br
.ti -1c
.RI "void \fBTLVFNodeStart\fP ()"
.br
.ti -1c
.RI "void \fBTLVFNodeEnd\fP ()"
.br
.ti -1c
.RI "void \fBATVFNodeStart\fP ()"
.br
.ti -1c
.RI "void \fBATVFNodeEnd\fP ()"
.br
.ti -1c
.RI "void \fBsfvgOptStart\fP ()"
.br
.ti -1c
.RI "void \fBsfvgOptEnd\fP ()"
.br
.ti -1c
.RI "void \fBaddToSources\fP (const \fBSVFGNode\fP *node)"
.br
.ti -1c
.RI "void \fBaddToSinks\fP (const \fBSVFGNode\fP *node)"
.br
.ti -1c
.RI "void \fBaddToForwardSlice\fP (const \fBSVFGNode\fP *node)"
.br
.ti -1c
.RI "void \fBaddToBackwardSlice\fP (const \fBSVFGNode\fP *node)"
.br
.ti -1c
.RI "bool \fBinForwardSlice\fP (const \fBSVFGNode\fP *node) const"
.br
.ti -1c
.RI "bool \fBinBackwardSlice\fP (const \fBSVFGNode\fP *node) const"
.br
.ti -1c
.RI "bool \fBisSource\fP (const \fBSVFGNode\fP *node) const"
.br
.ti -1c
.RI "bool \fBisSink\fP (const \fBSVFGNode\fP *node) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVFGStat::SVFGStat (\fBSVFG\fP * g)"
Constructor 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
