.TH "SVF::ArgumentVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ArgumentVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::VFGNode\fP\&.
.PP
Inherited by \fBSVF::ActualParmVFGNode\fP, \fBSVF::ActualRetVFGNode\fP, \fBSVF::FormalParmVFGNode\fP, and \fBSVF::FormalRetVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgumentVFGNode\fP (NodeID id, const \fBPAGNode\fP *p, \fBVFGNodeK\fP k)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "bool \fBisPTANode\fP () const"
.br
.RI "Whether this argument node is of pointer type (used for pointer analysis)\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBArgumentVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBPAGNode\fP * \fBparam\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
