.TH "SVF::IndirectSVFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::IndirectSVFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SVFGEdge\&.h>\fP
.PP
Inherits \fBSVF::VFGEdge\fP\&.
.PP
Inherited by \fBSVF::CallIndSVFGEdge\fP, \fBSVF::IntraIndSVFGEdge\fP, \fBSVF::RetIndSVFGEdge\fP, and \fBSVF::ThreadMHPIndSVFGEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Set< const \fBMRVer\fP * > \fBMRVerSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndirectSVFGEdge\fP (\fBVFGNode\fP *s, \fBVFGNode\fP *d, \fBGEdgeFlag\fP k)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "bool \fBaddPointsTo\fP (const PointsTo &c)"
.br
.RI "Handle memory region\&. "
.ti -1c
.RI "const PointsTo & \fBgetPointsTo\fP () const"
.br
.ti -1c
.RI "MRVerSet & \fBgetMRVer\fP ()"
.br
.ti -1c
.RI "bool \fBaddMrVer\fP (const \fBMRVer\fP *mr)"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIndirectSVFGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSVFG\fP edge representing indirect value-flows from a caller to its callee at a callsite 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
