.TH "SVF::CHEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CHEdge
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericEdge< NodeTy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCHEDGETYPE\fP { \fBINHERITANCE\fP = 0x1, \fBINSTANTCE\fP = 0x2 }"
.br
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBCHNode\fP, \fBCHEdge\fP >::GEdgeSetTy \fBCHEdgeSetTy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHEdge\fP (\fBCHNode\fP *s, \fBCHNode\fP *d, CHEDGETYPE et, \fBGEdgeFlag\fP k=0)"
.br
.ti -1c
.RI "CHEDGETYPE \fBgetEdgeType\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
