.TH "SVF::OfflineConsG" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::OfflineConsG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OfflineConsG\&.h>\fP
.PP
Inherits \fBSVF::ConstraintGraph\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSCCDetection\fP< \fBOfflineConsG\fP * > \fBOSCC\fP"
.br
.ti -1c
.RI "typedef Set< \fBLoadCGEdge\fP * > \fBLoadEdges\fP"
.br
.ti -1c
.RI "typedef Set< \fBStoreCGEdge\fP * > \fBStoreEdges\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOfflineConsG\fP (\fBPAG\fP *p)"
.br
.ti -1c
.RI "bool \fBhasOCGRep\fP (NodeID node) const"
.br
.ti -1c
.RI "NodeID \fBgetOCGRep\fP (NodeID node) const"
.br
.ti -1c
.RI "const NodeToRepMap & \fBgetOCGRepMap\fP () const"
.br
.ti -1c
.RI "bool \fBisaRef\fP (NodeID node) const"
.br
.ti -1c
.RI "bool \fBhasRef\fP (NodeID node) const"
.br
.ti -1c
.RI "NodeID \fBgetRef\fP (NodeID node) const"
.br
.ti -1c
.RI "void \fBsolveOfflineSCC\fP (\fBOSCC\fP *oscc)"
.br
.ti -1c
.RI "void \fBbuildOfflineMap\fP (\fBOSCC\fP *oscc)"
.br
.ti -1c
.RI "void \fBdump\fP (std::string name)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBhasNorRep\fP (NodeID nor) const"
.br
.ti -1c
.RI "void \fBsetNorRep\fP (NodeID nor, NodeID rep)"
.br
.ti -1c
.RI "NodeID \fBgetNorRep\fP (NodeID nor) const"
.br
.ti -1c
.RI "NodeID \fBsolveRep\fP (\fBOSCC\fP *oscc, NodeID rep)"
.br
.ti -1c
.RI "void \fBbuildOfflineCG\fP ()"
.br
.ti -1c
.RI "bool \fBaddRefLoadEdge\fP (NodeID src, NodeID dst)"
.br
.ti -1c
.RI "bool \fBaddRefStoreEdge\fP (NodeID src, NodeID dst)"
.br
.ti -1c
.RI "bool \fBcreateRefNode\fP (NodeID nodeId)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NodeSet \fBrefNodes\fP"
.br
.ti -1c
.RI "NodeToRepMap \fBnodeToRefMap\fP"
.br
.ti -1c
.RI "NodeToRepMap \fBnorToRepMap\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Offline constraint graph for \fBAndersen\fP's analysis\&. In OCG, a 'ref' node is used to represent the point-to set of a constraint node\&. 'Nor' means a constraint node of its corresponding ref node\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool OfflineConsG::addRefLoadEdge (NodeID src, NodeID dst)\fC [protected]\fP"
Add a copy edge between the ref node of src node and dst node, while meeting a LOAD constraint\&. 
.SS "bool OfflineConsG::addRefStoreEdge (NodeID src, NodeID dst)\fC [protected]\fP"
Add a copy edge between src node and the ref node of dst node, while meeting a STORE constraint\&. 
.SS "void OfflineConsG::buildOfflineCG ()\fC [protected]\fP"
Builder of offline constraint graph 
.SS "void OfflineConsG::buildOfflineMap (\fBOSCC\fP * oscc)"
Build offline node to rep map, which only collect nodes having a ref node 
.SS "bool OfflineConsG::createRefNode (NodeID nodeId)\fC [protected]\fP"
Create a ref node for a constraint node if it does not have one 
.SS "void OfflineConsG::dump (std::string name)"
Dump offline constraint graph 
.SS "void OfflineConsG::solveOfflineSCC (\fBOSCC\fP * oscc)"
Use a offline SCC detector to solve node relations in OCG\&. Generally, the 'oscc' should be solved first\&. 
.SS "NodeID OfflineConsG::solveRep (\fBOSCC\fP * oscc, NodeID rep)\fC [protected]\fP"
The rep nodes of offline constraint graph are possible to be 'ref' nodes\&. These nodes should be replaced by one of its sub nodes which is not a ref node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
