.TH "SVF::BreakConstantGEPs" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::BreakConstantGEPs
.SH SYNOPSIS
.br
.PP
.PP
Inherits ModulePass\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "StringRef \fBgetPassName\fP () const"
.br
.ti -1c
.RI "virtual bool \fBrunOnModule\fP (Module &M)"
.br
.ti -1c
.RI "virtual void \fBgetAnalysisUsage\fP (AnalysisUsage &AU) const"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static char \fBID\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
