.TH "SVF::CHNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CHNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericNode< NodeTy, EdgeTy >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCLASSATTR\fP { \fBPURE_ABSTRACT\fP = 0x1, \fBMULTI_INHERITANCE\fP = 0x2, \fBTEMPLATE\fP = 0x04 }"
.br
.ti -1c
.RI "typedef std::vector< const \fBSVFFunction\fP * > \fBFuncVector\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHNode\fP (const std::string name, NodeID i=0, \fBGNodeK\fP k=0)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetFlag\fP (CLASSATTR mask)"
.br
.RI "Flags\&. "
.ti -1c
.RI "bool \fBhasFlag\fP (CLASSATTR mask) const"
.br
.ti -1c
.RI "void \fBsetPureAbstract\fP ()"
.br
.RI "Attribute\&. "
.ti -1c
.RI "void \fBsetMultiInheritance\fP ()"
.br
.ti -1c
.RI "void \fBsetTemplate\fP ()"
.br
.ti -1c
.RI "bool \fBisPureAbstract\fP () const"
.br
.ti -1c
.RI "bool \fBisMultiInheritance\fP () const"
.br
.ti -1c
.RI "bool \fBisTemplate\fP () const"
.br
.ti -1c
.RI "void \fBaddVirtualFunctionVector\fP (FuncVector vfuncvec)"
.br
.ti -1c
.RI "const std::vector< FuncVector > & \fBgetVirtualFunctionVectors\fP () const"
.br
.ti -1c
.RI "void \fBgetVirtualFunctions\fP (u32_t idx, FuncVector &virtualFunctions) const"
.br
.ti -1c
.RI "const GlobalValue * \fBgetVTable\fP () const"
.br
.ti -1c
.RI "void \fBsetVTable\fP (const GlobalValue *vtbl)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
