.TH "SVF::CallPE" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CallPE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAGEdge\&.h>\fP
.PP
Inherits \fBSVF::PAGEdge\fP\&.
.PP
Inherited by \fBSVF::TDForkPE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallPE\fP (\fBPAGNode\fP *s, \fBPAGNode\fP *d, const \fBCallBlockNode\fP *i, GEdgeKind k=PAGEdge::Call)"
.br
.RI "constructor "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallInst\fP () const"
.br
.RI "Get method for the call instruction\&. "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallSite\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCallPE\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Call edge 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
