.TH "SVF::IntraBlockNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::IntraBlockNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICFGNode\&.h>\fP
.PP
Inherits \fBSVF::ICFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraBlockNode\fP (NodeID id, const Instruction *i)"
.br
.ti -1c
.RI "const Instruction * \fBgetInst\fP () const"
.br
.ti -1c
.RI "const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIntraBlockNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBICFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericICFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBICFG\fP node stands for a program statement 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
