.TH "SVF::ValPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ValPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PAGNode\fP\&.
.PP
Inherited by \fBSVF::DummyValPN\fP, and \fBSVF::GepValPN\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValPN\fP (const Value *val, NodeID i, \fBPNODEK\fP ty=ValNode)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of a LLVM value\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBValPN\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
