.TH "SVF::PTASCEV" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PTASCEV
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataFlowUtil\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPTASCEV\fP (const Value *p, const SCEV *s, ScalarEvolution *SE)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBPTASCEV\fP (const \fBPTASCEV\fP &ptase)"
.br
.RI "Copy Constructor\&. "
.ti -1c
.RI "virtual \fB~PTASCEV\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPTASCEV\fP &rhs) const"
.br
.ti -1c
.RI "\fBPTASCEV\fP & \fBoperator=\fP (const \fBPTASCEV\fP &rhs)"
.br
.RI "Overloading operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPTASCEV\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBPTASCEV\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const SCEV * \fBscev\fP"
.br
.ti -1c
.RI "const Value * \fBstart\fP"
.br
.ti -1c
.RI "const Value * \fBstep\fP"
.br
.ti -1c
.RI "const Value * \fBptr\fP"
.br
.ti -1c
.RI "bool \fBinloop\fP"
.br
.ti -1c
.RI "unsigned \fBtripcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for SCEV collected from function pass ScalarEvolution 
.SH "Member Function Documentation"
.PP 
.SS "bool SVF::PTASCEV::operator< (const \fBPTASCEV\fP & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
