.TH "SVF::AndersenBase" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::WPASolver< GraphType >\fP, and \fBSVF::BVDataPTAImpl\fP\&.
.PP
Inherited by \fBSVF::Andersen\fP, \fBSVF::Steensgaard\fP, and \fBSVF::TypeAnalysis\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenBase\fP (\fBPAG\fP *_pag, \fBPTATY\fP type=\fBAndersen_BASE\fP, bool alias_check=true)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~AndersenBase\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual void \fBanalyze\fP ()"
.br
.RI "\fBAndersen\fP analysis\&. "
.ti -1c
.RI "virtual void \fBinitialize\fP ()"
.br
.RI "Initialize analysis\&. "
.ti -1c
.RI "virtual void \fBfinalize\fP ()"
.br
.RI "Finalize analysis\&. "
.ti -1c
.RI "\fBConstraintGraph\fP * \fBgetConstraintGraph\fP ()"
.br
.RI "Get constraint graph\&. "
.ti -1c
.RI "void \fBprintStat\fP ()"
.br
.RI "dump statistics "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBAndersenBase\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPointerAnalysis\fP *pta)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Size_t \fBnumOfProcessedAddr\fP = 0"
.br
.RI "Statistics\&. "
.ti -1c
.RI "static Size_t \fBnumOfProcessedCopy\fP = 0"
.br
.RI "Number of processed Addr edge\&. "
.ti -1c
.RI "static Size_t \fBnumOfProcessedGep\fP = 0"
.br
.RI "Number of processed Copy edge\&. "
.ti -1c
.RI "static Size_t \fBnumOfProcessedLoad\fP = 0"
.br
.RI "Number of processed Gep edge\&. "
.ti -1c
.RI "static Size_t \fBnumOfProcessedStore\fP = 0"
.br
.RI "Number of processed Load edge\&. "
.ti -1c
.RI "static Size_t \fBnumOfSfrs\fP = 0"
.br
.RI "Number of processed Store edge\&. "
.ti -1c
.RI "static Size_t \fBnumOfFieldExpand\fP = 0"
.br
.ti -1c
.RI "static Size_t \fBnumOfSCCDetection\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfSCCDetection\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfSCCMerges\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfCollapse\fP = 0"
.br
.ti -1c
.RI "static Size_t \fBAveragePointsToSetSize\fP = 0"
.br
.ti -1c
.RI "static Size_t \fBMaxPointsToSetSize\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfProcessCopyGep\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfProcessLoadStore\fP = 0"
.br
.ti -1c
.RI "static double \fBtimeOfUpdateCallGraph\fP = 0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConstraintGraph\fP * \fBconsCG\fP"
.br
.RI "Constraint Graph\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void AndersenBase::analyze ()\fC [virtual]\fP"

.PP
\fBAndersen\fP analysis\&. \fBAndersen\fP analysis Initialization for the Solver
.PP
Implements \fBSVF::PointerAnalysis\fP\&.
.PP
Reimplemented in \fBSVF::TypeAnalysis\fP\&.
.SS "void AndersenBase::finalize (void)\fC [virtual]\fP"

.PP
Finalize analysis\&. Finalize analysis dump constraint graph if PAGDotGraph flag is enabled
.PP
Reimplemented from \fBSVF::PointerAnalysis\fP\&.
.PP
Reimplemented in \fBSVF::TypeAnalysis\fP, and \fBSVF::Andersen\fP\&.
.SS "void AndersenBase::initialize ()\fC [virtual]\fP"

.PP
Initialize analysis\&. Initilize analysis Build \fBPAG\fP
.PP
Build Constraint Graph
.PP
Create statistic class
.PP
Reimplemented from \fBSVF::PointerAnalysis\fP\&.
.PP
Reimplemented in \fBSVF::TypeAnalysis\fP, \fBSVF::AndersenSFR\fP, \fBSVF::AndersenHLCD\fP, \fBSVF::AndersenHCD\fP, and \fBSVF::Andersen\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
