.TH "SVF::VersionedFlowSensitiveStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::VersionedFlowSensitiveStat
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersionedFlowSensitiveStat\fP (\fBVersionedFlowSensitive\fP *pta)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVersionedFlowSensitive\fP * \fBvfspta\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
