.TH "SVF::NormalGepPE" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::NormalGepPE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAGEdge\&.h>\fP
.PP
Inherits \fBSVF::GepPE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNormalGepPE\fP (\fBPAGNode\fP *s, \fBPAGNode\fP *d, const \fBLocationSet\fP &l)"
.br
.RI "constructor "
.ti -1c
.RI "u32_t \fBgetOffset\fP () const"
.br
.RI "offset of the gep edge "
.ti -1c
.RI "const \fBLocationSet\fP & \fBgetLocationSet\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBNormalGepPE\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGepPE\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Gep edge with a fixed offset 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
