.TH "SVF::InterDisjointMRG" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::InterDisjointMRG
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemPartition\&.h>\fP
.PP
Inherits \fBSVF::IntraDisjointMRG\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterDisjointMRG\fP (\fBBVDataPTAImpl\fP *p, bool ptrOnly)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpartitionMRs\fP ()"
.br
.RI "Partition regions\&. "
.ti -1c
.RI "virtual void \fBgetMRsForLoad\fP (\fBMRSet\fP &aliasMRs, const PointsTo &cpts, const \fBSVFFunction\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Create memory regions which don't have intersections with each other in the whole program scope\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual void SVF::InterDisjointMRG::getMRsForLoad (\fBMRSet\fP & aliasMRs, const PointsTo & cpts, const \fBSVFFunction\fP *)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
Get memory regions to be inserted at a load statement\&. 
.PP
\fBParameters\fP
.RS 4
\fIcpts\fP The conditional points-to set of load statement\&. 
.br
\fIfun\fP The function being analyzed\&. 
.br
\fImrs\fP Memory region set contains all possible target memory regions\&. 
.RE
.PP

.PP
Reimplemented from \fBSVF::IntraDisjointMRG\fP\&.
.SS "void InterDisjointMRG::partitionMRs ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Partition regions\&. Generate disjoint cpts\&.
.PP
Create memory regions\&.
.PP
Reimplemented from \fBSVF::IntraDisjointMRG\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
