.TH "SVF::DummyObjPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DummyObjPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ObjPN\fP\&.
.PP
Inherited by \fBSVF::CloneDummyObjPN\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDummyObjPN\fP (NodeID i, const \fBMemObj\fP *m, \fBPNODEK\fP ty=DummyObjNode)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of this node\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBDummyObjPN\fP *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
