.TH "SVF::AndersenStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WPAStat\&.h>\fP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenStat\fP (\fBAndersenBase\fP *p)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP ()"
.br
.ti -1c
.RI "void \fBcollectCycleInfo\fP (\fBConstraintGraph\fP *consCG)"
.br
.ti -1c
.RI "void \fBstatNullPtr\fP ()"
.br
.ti -1c
.RI "void \fBconstraintGraphStat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u32_t \fB_NumOfNullPtr\fP"
.br
.ti -1c
.RI "u32_t \fB_NumOfConstantPtr\fP"
.br
.ti -1c
.RI "u32_t \fB_NumOfBlackholePtr\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const char * \fBCollapseTime\fP = 'CollapseTime'"
.br
.ti -1c
.RI "static u32_t \fB_MaxPtsSize\fP = 0"
.br
.ti -1c
.RI "static u32_t \fB_NumOfCycles\fP = 0"
.br
.ti -1c
.RI "static u32_t \fB_NumOfPWCCycles\fP = 0"
.br
.ti -1c
.RI "static u32_t \fB_NumOfNodesInCycles\fP = 0"
.br
.ti -1c
.RI "static u32_t \fB_MaxNumOfNodesInSCC\fP = 0"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Statistics of \fBAndersen\fP's analysis 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AndersenStat::AndersenStat (\fBAndersenBase\fP * p)"
Constructor 
.SH "Member Function Documentation"
.PP 
.SS "void AndersenStat::collectCycleInfo (\fBConstraintGraph\fP * consCG)"
Collect cycle information 
.SS "void AndersenStat::performStat ()\fC [virtual]\fP"
Start here 
.PP
Reimplemented from \fBSVF::PTAStat\fP\&.
.SS "void AndersenStat::statNullPtr ()"
Stat null pointers TODO: change the condition here to fetch the points-to set

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
