.TH "SVF::FlowSensitiveStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FlowSensitiveStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WPAStat\&.h>\fP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef FlowSensitive::DFInOutMap \fBDFInOutMap\fP"
.br
.ti -1c
.RI "typedef FlowSensitive::PtsMap \fBPtsMap\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlowSensitiveStat\fP (\fBFlowSensitive\fP *pta)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFlowSensitive\fP * \fBfspta\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Statistics of flow-sensitive analysis 
.SH "Member Function Documentation"
.PP 
.SS "void FlowSensitiveStat::performStat ()\fC [virtual]\fP"
Start statistics \fBSVFG\fP nodes\&.
.PP
Reimplemented from \fBSVF::PTAStat\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
