.TH "SVF::GlobalBlockNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::GlobalBlockNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICFGNode\&.h>\fP
.PP
Inherits \fBSVF::ICFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalBlockNode\fP (NodeID id)"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGlobalBlockNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBICFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericICFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Unique \fBICFG\fP node stands for all global initializations 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
