.TH "SVF::MSSACHI< Cond >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MSSACHI< Cond >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSSAMuChi\&.h>\fP
.PP
Inherits \fBSVF::MSSADEF\fP\&.
.PP
Inherited by \fBSVF::CallCHI< Cond >\fP, \fBSVF::EntryCHI< Cond >\fP, and \fBSVF::StoreCHI< Cond >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MSSADEF::DEFTYPE \fBCHITYPE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMSSACHI\fP (CHITYPE t, const \fBMemRegion\fP *m, Cond c)"
.br
.RI "Constructor/Destructer for \fBMSSACHI\fP\&. "
.ti -1c
.RI "void \fBsetOpVer\fP (\fBMRVer\fP *v)"
.br
.RI "Set operand ver\&. "
.ti -1c
.RI "\fBMRVer\fP * \fBgetOpVer\fP () const"
.br
.RI "Get operand ver\&. "
.ti -1c
.RI "Cond \fBgetCond\fP () const"
.br
.RI "Get condition\&. "
.ti -1c
.RI "virtual void \fBdump\fP ()"
.br
.RI "Print CHI\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMSSACHI\fP *chi)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMSSADEF\fP *chi)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class Cond>
.br
class SVF::MSSACHI< Cond >"
Indirect Memory Write 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
