.TH "SVF::ICFGBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ICFGBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< const Instruction * > \fBInstVec\fP"
.br
.ti -1c
.RI "typedef Set< const Instruction * > \fBBBSet\fP"
.br
.ti -1c
.RI "typedef \fBFIFOWorkList\fP< const Instruction * > \fBWorkList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBICFGBuilder\fP (\fBICFG\fP *i)"
.br
.ti -1c
.RI "void \fBbuild\fP (\fBSVFModule\fP *svfModule)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ICFGBuilder::build (\fBSVFModule\fP * svfModule)"
Create \fBICFG\fP nodes and edges 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
