.TH "SVF::RetPE" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::RetPE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAGEdge\&.h>\fP
.PP
Inherits \fBSVF::PAGEdge\fP\&.
.PP
Inherited by \fBSVF::TDJoinPE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRetPE\fP (\fBPAGNode\fP *s, \fBPAGNode\fP *d, const \fBCallBlockNode\fP *i, GEdgeKind k=PAGEdge::Ret)"
.br
.RI "constructor "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallInst\fP () const"
.br
.RI "Get method for call instruction at caller\&. "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallSite\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBRetPE\fP *)"
.br
.RI "the callsite instruction return to "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Return edge 
.SH "Member Function Documentation"
.PP 
.SS "static bool SVF::RetPE::classof (const \fBRetPE\fP *)\fC [inline]\fP, \fC [static]\fP"

.PP
the callsite instruction return to Methods for support type inquiry through isa, cast, and dyn_cast: 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
