.TH "SVF::AndersenWaveDiffWithType" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenWaveDiffWithType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Andersen\&.h>\fP
.PP
Inherits \fBSVF::AndersenWaveDiff\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenWaveDiffWithType\fP (\fBPAG\fP *_pag, \fBPTATY\fP type=\fBAndersenWaveDiffWithType_WPA\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAndersenWaveDiffWithType\fP * \fBcreateAndersenWaveDiffWithType\fP (\fBPAG\fP *p)"
.br
.RI "Create an singleton instance directly instead of invoking llvm pass manager\&. "
.ti -1c
.RI "static void \fBreleaseAndersenWaveDiffWithType\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual NodeStack & \fBSCCDetect\fP ()"
.br
.RI "SCC detection\&. "
.ti -1c
.RI "void \fBmergeTypeOfNodes\fP (const NodeBS &nodes)"
.br
.RI "merge types of nodes in a cycle "
.ti -1c
.RI "virtual void \fBprocessCast\fP (const \fBConstraintEdge\fP *edge)"
.br
.RI "process 'bitcast' \fBCopyCGEdge\fP "
.ti -1c
.RI "void \fBupdateObjType\fP (const Type *type, const PointsTo &objs)"
.br
.RI "update type of objects when process 'bitcast' \fBCopyCGEdge\fP "
.ti -1c
.RI "void \fBprocessTypeMismatchedGep\fP (NodeID obj, const Type *type)"
.br
.RI "process mismatched gep edges "
.ti -1c
.RI "virtual bool \fBmatchType\fP (NodeID ptrid, NodeID objid, const \fBNormalGepCGEdge\fP *normalGepEdge)"
.br
.RI "match types for Gep Edges "
.ti -1c
.RI "virtual void \fBaddTypeForGepObjNode\fP (NodeID id, const \fBNormalGepCGEdge\fP *normalGepEdge)"
.br
.RI "add type for newly created GepObjNode "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Wave propagation with diff points-to set with type filter\&. 
.SH "Member Function Documentation"
.PP 
.SS "void AndersenWaveDiffWithType::mergeTypeOfNodes (const NodeBS & nodes)\fC [protected]\fP"

.PP
merge types of nodes in a cycle collect types in a cycle
.PP
merge types of nodes in a cycle
.SS "NodeStack & AndersenWaveDiffWithType::SCCDetect ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
SCC detection\&. merge types of nodes in SCC
.PP
Reimplemented from \fBSVF::Andersen\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
