.TH "SVF::CondVar< Cond >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CondVar< Cond >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConditionalPT\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondVar\fP (const Cond &cond, NodeID id)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCondVar\fP (const \fBCondVar\fP &conVar)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "\fBCondVar\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBCondVar\fP & \fBoperator=\fP (const \fBCondVar\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCondVar\fP &rhs) const"
.br
.ti -1c
.RI "const Cond & \fBget_cond\fP () const"
.br
.ti -1c
.RI "NodeID \fBget_id\fP () const"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCondVar\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCondVar\fP &rhs) const"
.br
.in -1c
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBraw_ostream\fP & \fBoperator<<\fP (\fBraw_ostream\fP &o, const \fBCondVar\fP< Cond > &cvar)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Cond>
.br
class SVF::CondVar< Cond >"
Conditional Variable (c,v) A context/path condition A variable NodeID 
.SH "Member Function Documentation"
.PP 
.SS "template<class Cond > bool \fBSVF::CondVar\fP< Cond >::operator< (const \fBCondVar\fP< Cond > & rhs) const\fC [inline]\fP"
Less than implementation\&. 
.SS "template<class Cond > bool \fBSVF::CondVar\fP< Cond >::operator== (const \fBCondVar\fP< Cond > & rhs) const\fC [inline]\fP"
Comparison between two elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
