.TH "SVF::ConstraintEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ConstraintEdge
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::GenericEdge< NodeTy >\fP\&.
.PP
Inherited by \fBSVF::AddrCGEdge\fP, \fBSVF::CopyCGEdge\fP, \fBSVF::GepCGEdge\fP, \fBSVF::LoadCGEdge\fP, and \fBSVF::StoreCGEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBConstraintEdgeK\fP { \fBAddr\fP, \fBCopy\fP, \fBStore\fP, \fBLoad\fP, \fBNormalGep\fP, \fBVariantGep\fP }"
.br
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBConstraintNode\fP, \fBConstraintEdge\fP >::GEdgeSetTy \fBConstraintEdgeSetTy\fP"
.br
.RI "Constraint edge type\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstraintEdge\fP (\fBConstraintNode\fP *s, \fBConstraintNode\fP *d, \fBConstraintEdgeK\fP k, EdgeID id=0)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~ConstraintEdge\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "EdgeID \fBgetEdgeID\fP () const"
.br
.RI "Return edge ID\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericConsEdgeTy\fP *edge)"
.br
.RI "ClassOf\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSVF::ConstraintEdge::ConstraintEdgeK\fP"
five kinds of constraint graph edges Gep edge is used for field sensitivity 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
