.TH "SVF::ActualINSVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ActualINSVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::MRSVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActualINSVFGNode\fP (NodeID id, const \fBMemSSA::CALLMU\fP *m, const \fBCallBlockNode\fP *c)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallSite\fP () const"
.br
.RI "Callsite\&. "
.ti -1c
.RI "const \fBMemSSA::CALLMU\fP * \fBgetCallMU\fP () const"
.br
.RI "\fBCallMU\fP\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBActualINSVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
