.TH "SVF::VariantGepCGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::VariantGepCGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConsGEdge\&.h>\fP
.PP
Inherits \fBSVF::GepCGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVariantGepCGEdge\fP (\fBConstraintNode\fP *s, \fBConstraintNode\fP *d, EdgeID id)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVariantGepCGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGepCGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBConstraintEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericConsEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Gep edge with variant offset size 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
