.TH "SVF::FormalParmVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FormalParmVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ArgumentVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormalParmVFGNode\fP (NodeID id, const \fBPAGNode\fP *n, const \fBSVFFunction\fP *f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBPAGNode\fP * \fBgetParam\fP () const"
.br
.RI "Return parameter\&. "
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetFun\fP () const"
.br
.RI "Return function\&. "
.ti -1c
.RI "void \fBaddCallPE\fP (const \fBCallPE\fP *call)"
.br
.RI "Return call edge\&. "
.in -1c
.in +1c
.ti -1c
.RI "CallPESet::const_iterator \fBcallPEBegin\fP () const"
.br
.ti -1c
.RI "CallPESet::const_iterator \fBcallPEEnd\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBFormalParmVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBArgumentVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "CallPESet::const_iterator SVF::FormalParmVFGNode::callPEBegin () const\fC [inline]\fP"
Call edge iterator 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
