.TH "SVF::ExtAPI" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ExtAPI
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBextf_t\fP { \fBEFT_NOOP\fP = 0, \fBEFT_ALLOC\fP, \fBEFT_REALLOC\fP, \fBEFT_FREE\fP, \fBEFT_NOSTRUCT_ALLOC\fP, \fBEFT_STAT\fP, \fBEFT_STAT2\fP, \fBEFT_L_A0\fP, \fBEFT_L_A1\fP, \fBEFT_L_A2\fP, \fBEFT_L_A8\fP, \fBEFT_L_A0__A0R_A1\fP, \fBEFT_L_A0__A0R_A1R\fP, \fBEFT_A1R_A0R\fP, \fBEFT_A3R_A1R_NS\fP, \fBEFT_A1R_A0\fP, \fBEFT_A2R_A1\fP, \fBEFT_A4R_A1\fP, \fBEFT_L_A0__A2R_A0\fP, \fBEFT_L_A0__A1_A0\fP, \fBEFT_A0R_NEW\fP, \fBEFT_A1R_NEW\fP, \fBEFT_A2R_NEW\fP, \fBEFT_A4R_NEW\fP, \fBEFT_A11R_NEW\fP, \fBEFT_STD_RB_TREE_INSERT_AND_REBALANCE\fP, \fBEFT_STD_RB_TREE_INCREMENT\fP, \fBEFT_STD_LIST_HOOK\fP, \fBCPP_EFT_A0R_A1\fP, \fBCPP_EFT_A0R_A1R\fP, \fBCPP_EFT_A1R\fP, \fBEFT_CXA_BEGIN_CATCH\fP, \fBCPP_EFT_DYNAMIC_CAST\fP, \fBEFT_OTHER\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "extf_t \fBget_type\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBhas_static\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBhas_static2\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_alloc\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_arg_alloc\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "int \fBget_alloc_arg_pos\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBno_struct_alloc\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_dealloc\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_noop\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_realloc\fP (const \fBSVFFunction\fP *F) const"
.br
.ti -1c
.RI "bool \fBis_ext\fP (const \fBSVFFunction\fP *F)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBExtAPI\fP * \fBgetExtAPI\fP ()"
.br
.RI "Singleton design here to make sure we only have one instance during whole analysis\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
