.TH "SVF::CallIndSVFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CallIndSVFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SVFGEdge\&.h>\fP
.PP
Inherits \fBSVF::IndirectSVFGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallIndSVFGEdge\fP (\fBVFGNode\fP *s, \fBVFGNode\fP *d, CallSiteID id)"
.br
.ti -1c
.RI "CallSiteID \fBgetCallSiteId\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCallIndSVFGEdge\fP *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIndirectSVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSVFG\fP call edge representing indirect value-flows from a caller to its callee at a callsite 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
