.TH "SVF::CxtStmt" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CxtStmt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CxtStmt\&.h>\fP
.PP
Inherited by \fBSVF::CxtThreadStmt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCxtStmt\fP (const CallStrCxt &c, const Instruction *f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCxtStmt\fP (const \fBCxtStmt\fP &ctm)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "virtual \fB~CxtStmt\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const CallStrCxt & \fBgetContext\fP () const"
.br
.RI "Return current context\&. "
.ti -1c
.RI "const Instruction * \fBgetStmt\fP () const"
.br
.RI "Return current statement\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCxtStmt\fP &rhs) const"
.br
.ti -1c
.RI "\fBCxtStmt\fP & \fBoperator=\fP (const \fBCxtStmt\fP &rhs)"
.br
.RI "Overloading operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCxtStmt\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCxtStmt\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "std::string \fBcxtToStr\fP () const"
.br
.RI "Return context in string format\&. "
.ti -1c
.RI "void \fBdump\fP () const"
.br
.RI "Dump \fBCxtStmt\fP\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "CallStrCxt \fBcxt\fP"
.br
.ti -1c
.RI "const Instruction * \fBinst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context-sensitive thread statement <c,s> 
.SH "Member Function Documentation"
.PP 
.SS "bool SVF::CxtStmt::operator< (const \fBCxtStmt\fP & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
