.TH "SVF::LocationSet" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::LocationSet
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLSRelation\fP { \fBNonOverlap\fP, \fBOverlap\fP, \fBSubset\fP, \fBSuperset\fP, \fBSame\fP }"
.br
.ti -1c
.RI "typedef FieldInfo::ElemNumStridePairVec \fBElemNumStridePairVec\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocationSet\fP (Size_t o=0)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBLocationSet\fP (const \fBLocationSet\fP &ls)"
.br
.RI "Copy Constructor\&. "
.ti -1c
.RI "\fBLocationSet\fP (const \fBFieldInfo\fP &fi)"
.br
.RI "Initialization from \fBFieldInfo\fP\&. "
.ti -1c
.RI "\fBLocationSet\fP \fBoperator+\fP (const \fBLocationSet\fP &rhs) const"
.br
.RI "Overload operators\&. "
.ti -1c
.RI "const \fBLocationSet\fP & \fBoperator=\fP (const \fBLocationSet\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBLocationSet\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBLocationSet\fP &rhs) const"
.br
.ti -1c
.RI "Size_t \fBgetOffset\fP () const"
.br
.RI "Get methods\&. "
.ti -1c
.RI "Size_t \fBgetByteOffset\fP () const"
.br
.ti -1c
.RI "void \fBsetFldIdx\fP (Size_t idx)"
.br
.ti -1c
.RI "void \fBsetByteOffset\fP (Size_t os)"
.br
.ti -1c
.RI "const ElemNumStridePairVec & \fBgetNumStridePair\fP () const"
.br
.ti -1c
.RI "void \fBaddElemNumStridePair\fP (const NodePair &pair)"
.br
.ti -1c
.RI "bool \fBisConstantOffset\fP () const"
.br
.RI "Return TRUE if this is a constant location set\&. "
.ti -1c
.RI "bool \fBintersects\fP (const \fBLocationSet\fP &RHS) const"
.br
.RI "Return TRUE if we share any location in common with RHS\&. "
.ti -1c
.RI "std::string \fBdump\fP () const"
.br
.RI "Dump location set\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static LSRelation \fBcheckRelation\fP (const \fBLocationSet\fP &LHS, const \fBLocationSet\fP &RHS)"
.br
.RI "Check relations of two location sets\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSymbolTableInfo\fP"
.br
.ti -1c
.RI "class \fBLocSymTableInfo\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void LocationSet::addElemNumStridePair (const NodePair & pair)"
Add element num and stride pair The pair will not be added if any number of a stride is zero, because they will not have effect on the locations represented by this \fBLocationSet\fP\&.
.PP
Find the GCD stride

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
