.TH "SVF::ObjPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ObjPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PAGNode\fP\&.
.PP
Inherited by \fBSVF::DummyObjPN\fP, \fBSVF::FIObjPN\fP, and \fBSVF::GepObjPN\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBMemObj\fP * \fBgetMemObj\fP () const"
.br
.RI "Return memory object\&. "
.ti -1c
.RI "virtual const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of a LLVM value\&. "
.ti -1c
.RI "virtual const llvm::Type * \fBgetType\fP () const"
.br
.RI "Return type of the value\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBObjPN\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBObjPN\fP (const Value *val, NodeID i, const \fBMemObj\fP *m, \fBPNODEK\fP ty=ObjNode)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBMemObj\fP * \fBmem\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Data Documentation"
.PP 
.SS "const \fBMemObj\fP* SVF::ObjPN::mem\fC [protected]\fP"
memory object 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
