.TH "SVF::FileChecker" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FileChecker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileChecker\&.h>\fP
.PP
Inherits \fBSVF::LeakChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileChecker\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~FileChecker\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual bool \fBrunOnModule\fP (\fBSVFModule\fP *module)"
.br
.RI "We start from here\&. "
.ti -1c
.RI "bool \fBisSourceLikeFun\fP (const \fBSVFFunction\fP *fun)"
.br
.RI "Whether the function is a heap allocator/reallocator (allocate memory) "
.ti -1c
.RI "bool \fBisSinkLikeFun\fP (const \fBSVFFunction\fP *fun)"
.br
.RI "Whether the function is a heap deallocator (free/release memory) "
.ti -1c
.RI "void \fBreportBug\fP (\fBProgSlice\fP *slice)"
.br
.RI "Report file/close bugs\&. "
.ti -1c
.RI "void \fBreportNeverClose\fP (const \fBSVFGNode\fP *src)"
.br
.ti -1c
.RI "void \fBreportPartialClose\fP (const \fBSVFGNode\fP *src)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
File open/close checker to check consistency of file operations 
.SH "Member Function Documentation"
.PP 
.SS "virtual bool SVF::FileChecker::runOnModule (\fBSVFModule\fP * module)\fC [inline]\fP, \fC [virtual]\fP"

.PP
We start from here\&. start analysis
.PP
Reimplemented from \fBSVF::LeakChecker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
