.TH "SVF::SVFUtil::cast_retty_wrap< To, FromTy, FromTy >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFUtil::cast_retty_wrap< To, FromTy, FromTy >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBret_type\fP = typename \fBcast_retty_impl\fP< To, FromTy >::ret_type"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
