.TH "SVF::ICFGStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ICFGStat
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Set< const \fBICFGNode\fP * > \fBICFGNodeSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBICFGStat\fP (\fBICFG\fP *cfg)"
.br
.ti -1c
.RI "void \fBperformStat\fP ()"
.br
.ti -1c
.RI "void \fBperformStatforIFDS\fP ()"
.br
.ti -1c
.RI "void \fBcountStat\fP ()"
.br
.ti -1c
.RI "void \fBprintStat\fP (string statname)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
