.TH "SVF::VarArgPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::VarArgPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PAGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVarArgPN\fP (const \fBSVFFunction\fP *val, NodeID i)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of a LLVM value\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVarArgPN\fP *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
