.TH "SVF::CallCFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CallCFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICFGEdge\&.h>\fP
.PP
Inherits \fBSVF::ICFGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallCFGEdge\fP (\fBICFGNode\fP *s, \fBICFGNode\fP *d, const Instruction *c)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const Instruction * \fBgetCallSite\fP () const"
.br
.RI "Return callsite ID\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCallCFGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBICFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericICFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Call \fBICFG\fP edge representing parameter passing/return from a caller to a callee 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
