.TH "SVF::SVFModule" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFModule
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< const \fBSVFFunction\fP * > \fBFunctionSetType\fP"
.br
.ti -1c
.RI "typedef std::vector< Function * > \fBLLVMFunctionSetType\fP"
.br
.ti -1c
.RI "typedef std::vector< GlobalVariable * > \fBGlobalSetType\fP"
.br
.ti -1c
.RI "typedef std::vector< GlobalAlias * > \fBAliasSetType\fP"
.br
.ti -1c
.RI "typedef Map< const Function *, const \fBSVFFunction\fP * > \fBLLVMFun2SVFFunMap\fP"
.br
.ti -1c
.RI "typedef FunctionSetType::iterator \fBiterator\fP"
.br
.RI "Iterators type def\&. "
.ti -1c
.RI "typedef FunctionSetType::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef LLVMFunctionSetType::iterator \fBllvm_iterator\fP"
.br
.ti -1c
.RI "typedef LLVMFunctionSetType::const_iterator \fBllvm_const_iterator\fP"
.br
.ti -1c
.RI "typedef GlobalSetType::iterator \fBglobal_iterator\fP"
.br
.ti -1c
.RI "typedef GlobalSetType::const_iterator \fBconst_global_iterator\fP"
.br
.ti -1c
.RI "typedef AliasSetType::iterator \fBalias_iterator\fP"
.br
.ti -1c
.RI "typedef AliasSetType::const_iterator \fBconst_alias_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVFModule\fP (std::string moduleName='')"
.br
.RI "Constructors\&. "
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetSVFFunction\fP (const Function *fun) const"
.br
.ti -1c
.RI "const std::string & \fBgetModuleIdentifier\fP () const"
.br
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBaddFunctionSet\fP (Function *fun)"
.br
.ti -1c
.RI "void \fBaddGlobalSet\fP (GlobalVariable *glob)"
.br
.ti -1c
.RI "void \fBaddAliasSet\fP (GlobalAlias *alias)"
.br
.in -1c
.in -1c
.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "llvm_iterator \fBllvmFunBegin\fP ()"
.br
.ti -1c
.RI "llvm_const_iterator \fBllvmFunBegin\fP () const"
.br
.ti -1c
.RI "llvm_iterator \fBllvmFunEnd\fP ()"
.br
.ti -1c
.RI "llvm_const_iterator \fBllvmFunEnd\fP () const"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "global_iterator \fBglobal_begin\fP ()"
.br
.ti -1c
.RI "const_global_iterator \fBglobal_begin\fP () const"
.br
.ti -1c
.RI "global_iterator \fBglobal_end\fP ()"
.br
.ti -1c
.RI "const_global_iterator \fBglobal_end\fP () const"
.br
.ti -1c
.RI "alias_iterator \fBalias_begin\fP ()"
.br
.ti -1c
.RI "const_alias_iterator \fBalias_begin\fP () const"
.br
.ti -1c
.RI "alias_iterator \fBalias_end\fP ()"
.br
.ti -1c
.RI "const_alias_iterator \fBalias_end\fP () const"
.br
.in -1c
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetPagFromTXT\fP (std::string txt)"
.br
.ti -1c
.RI "static std::string \fBpagFileName\fP ()"
.br
.ti -1c
.RI "static bool \fBpagReadFromTXT\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "llvm_iterator SVF::SVFModule::llvmFunBegin ()\fC [inline]\fP"
Iterators 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
