.TH "SVF::cppUtil::ctir" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::cppUtil::ctir
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBderefMDName\fP = 'ctir'"
.br
.ti -1c
.RI "const std::string \fBvtMDName\fP = 'ctir\&.vt'"
.br
.ti -1c
.RI "const std::string \fBvtInitMDName\fP = 'ctir\&.vt\&.init'"
.br
.ti -1c
.RI "const uint32_t \fBmoduleFlagValue\fP = 1"
.br
.RI "Value we expect a ctir-annotated module to have\&. "
.in -1c
.SH "Detailed Description"
.PP 
Constants pertaining to CTir, for C and C++\&. TODO: move helper functions here too? 
.SH "Variable Documentation"
.PP 
.SS "const std::string SVF::cppUtil::ctir::derefMDName = 'ctir'"
On loads, stores, GEPs representing dereferences, and calls representing virtual calls\&. (The static type\&.) 
.SS "const std::string SVF::cppUtil::ctir::vtInitMDName = 'ctir\&.vt\&.init'"
On the bitcast of \fCthis\fP to i8*\&. (The class the constructor it corresponds to\&.) 
.SS "const std::string SVF::cppUtil::ctir::vtMDName = 'ctir\&.vt'"
On the (global) virtual table itself\&. (The class it corresponds to\&.) 
.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
