.TH "SVF::TypeSet" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::TypeSet
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef OrderedSet< \fBPTAType\fP > \fBTypeSetTy\fP"
.br
.ti -1c
.RI "typedef TypeSetTy::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef TypeSetTy::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.ti -1c
.RI "u32_t \fBsize\fP () const"
.br
.RI "Number of types contained\&. "
.ti -1c
.RI "bool \fBaddType\fP (const \fBPTAType\fP &type)"
.br
.RI "Add a ptatype\&. "
.ti -1c
.RI "bool \fBcontainType\fP (const \fBPTAType\fP &type) const"
.br
.RI "Contain a ptatype or not\&. "
.ti -1c
.RI "bool \fBintersect\fP (const \fBTypeSet\fP *typeset) const"
.br
.RI "Intersect with another typeset or not\&. "
.ti -1c
.RI "void \fBdumpTypes\fP () const"
.br
.RI "Dump all types in the typeset\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
