.TH "SVF::HareParForEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::HareParForEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThreadCallGraph\&.h>\fP
.PP
Inherits \fBSVF::PTACallGraphEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBPTACallGraphNode\fP, \fBHareParForEdge\fP >::GEdgeSetTy \fBParForEdgeSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHareParForEdge\fP (\fBPTACallGraphNode\fP *s, \fBPTACallGraphNode\fP *d, CallSiteID csId)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~HareParForEdge\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBHareParForEdge\fP *)"
.br
.RI "ClassOf\&. "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPTACallGraphEdge\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
hare_parallel_for edge from fork site to the entry of a start routine function 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
