.TH "SVF::CondStdSet< Element >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CondStdSet< Element >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConditionalPT\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef OrderedSet< Element >::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef OrderedSet< Element >::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCondStdSet\fP (const \fBCondStdSet\fP< Element > &cptsSet)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "bool \fBtest_and_set\fP (const Element &var)"
.br
.RI "Return true if the element is added\&. "
.ti -1c
.RI "bool \fBtest\fP (const Element &var) const"
.br
.RI "Return true if the element is in the set\&. "
.ti -1c
.RI "void \fBset\fP (const Element &var)"
.br
.RI "Add the element into set\&. "
.ti -1c
.RI "void \fBreset\fP (const Element &var)"
.br
.RI "Remove var from the set\&. "
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.RI "Set size\&. "
.ti -1c
.RI "unsigned \fBsize\fP () const"
.br
.ti -1c
.RI "unsigned \fBcount\fP () const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.RI "Clear set\&. "
.ti -1c
.RI "iterator \fBbegin\fP ()"
.br
.RI "Iterators\&. "
.ti -1c
.RI "iterator \fBend\fP ()"
.br
.ti -1c
.RI "iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "iterator \fBend\fP () const"
.br
.ti -1c
.RI "bool \fBoperator|=\fP (const \fBCondStdSet\fP< Element > &rhs)"
.br
.RI "Overload operators\&. "
.ti -1c
.RI "bool \fBoperator&=\fP (const \fBCondStdSet\fP< Element > &rhs)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCondStdSet\fP< Element > &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCondStdSet\fP< Element > &rhs) const"
.br
.ti -1c
.RI "\fBCondStdSet\fP< Element > & \fBoperator=\fP (const \fBCondStdSet\fP< Element > &rhs)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCondStdSet\fP< Element > &rhs) const"
.br
.ti -1c
.RI "bool \fBintersects\fP (const \fBCondStdSet\fP< Element > &rhs) const"
.br
.ti -1c
.RI "std::string \fBtoString\fP () const"
.br
.ti -1c
.RI "const ElementSet & \fBgetElementSet\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Element>
.br
class SVF::CondStdSet< Element >"
Conditional variable set 
.SH "Member Function Documentation"
.PP 
.SS "template<class Element > bool \fBSVF::CondStdSet\fP< Element >::intersects (const \fBCondStdSet\fP< Element > & rhs) const\fC [inline]\fP"
Return TRUE if this and RHS share common elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
