.TH "SVF::GepObjPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::GepObjPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ObjPN\fP\&.
.PP
Inherited by \fBSVF::CloneGepObjPN\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGepObjPN\fP (const \fBMemObj\fP *\fBmem\fP, NodeID i, const \fBLocationSet\fP &l, \fBPNODEK\fP ty=GepObjNode)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBLocationSet\fP & \fBgetLocationSet\fP () const"
.br
.RI "offset of the mem object "
.ti -1c
.RI "void \fBsetBaseNode\fP (NodeID base)"
.br
.RI "Set the base object from which this GEP node came from\&. "
.ti -1c
.RI "NodeID \fBgetBaseNode\fP (void) const"
.br
.RI "Return the base object from which this GEP node came from\&. "
.ti -1c
.RI "virtual const llvm::Type * \fBgetType\fP () const"
.br
.RI "Return the type of this gep object\&. "
.ti -1c
.RI "const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of a LLVM value\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGepObjPN\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBObjPN\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
