.TH "SVF::MemSSAStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MemSSAStat
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemSSAStat\fP (\fBMemSSA\fP *)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP ()"
.br
.ti -1c
.RI "virtual void \fBprintStat\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const char * \fBTotalTimeOfConstructMemSSA\fP = 'TotalMSSATime'"
.br
.RI "Total time for constructing memory SSA\&. "
.ti -1c
.RI "static const char * \fBTimeOfGeneratingMemRegions\fP = 'GenRegionTime'"
.br
.RI "Time for allocating regions\&. "
.ti -1c
.RI "static const char * \fBTimeOfCreateMUCHI\fP = 'GenMUCHITime'"
.br
.RI "Time for generating mu/chi for load/store/calls\&. "
.ti -1c
.RI "static const char * \fBTimeOfInsertingPHI\fP = 'InsertPHITime'"
.br
.RI "Time for inserting phis\&. "
.ti -1c
.RI "static const char * \fBTimeOfSSARenaming\fP = 'SSARenameTime'"
.br
.RI "Time for SSA rename\&. "
.ti -1c
.RI "static const char * \fBNumOfMaxRegion\fP = 'MaxRegSize'"
.br
.RI "Number of max points-to set in region\&. "
.ti -1c
.RI "static const char * \fBNumOfAveragePtsInRegion\fP = 'AverageRegSize'"
.br
.RI "Number of average points-to set in region\&. "
.ti -1c
.RI "static const char * \fBNumOfMemRegions\fP = 'MemRegions'"
.br
.RI "Number of memory regions\&. "
.ti -1c
.RI "static const char * \fBNumOfEntryChi\fP = 'FunEntryChi'"
.br
.RI "Number of function entry chi\&. "
.ti -1c
.RI "static const char * \fBNumOfRetMu\fP = 'FunRetMu'"
.br
.RI "Number of function return mu\&. "
.ti -1c
.RI "static const char * \fBNumOfCSChi\fP = 'CSChiNode'"
.br
.RI "Number of call site chi\&. "
.ti -1c
.RI "static const char * \fBNumOfCSMu\fP = 'CSMuNode'"
.br
.RI "Number of call site mu\&. "
.ti -1c
.RI "static const char * \fBNumOfLoadMu\fP = 'LoadMuNode'"
.br
.RI "Number of load mu\&. "
.ti -1c
.RI "static const char * \fBNumOfStoreChi\fP = 'StoreChiNode'"
.br
.RI "Number of store chi\&. "
.ti -1c
.RI "static const char * \fBNumOfMSSAPhi\fP = 'MSSAPhi'"
.br
.RI "Number of mssa phi\&. "
.ti -1c
.RI "static const char * \fBNumOfFunHasEntryChi\fP = 'FunHasEntryChi'"
.br
.RI "Number of functions which have entry chi\&. "
.ti -1c
.RI "static const char * \fBNumOfFunHasRetMu\fP = 'FunHasRetMu'"
.br
.RI "Number of functions which have return mu\&. "
.ti -1c
.RI "static const char * \fBNumOfCSHasChi\fP = 'CSHasChi'"
.br
.RI "Number of call sites which have chi\&. "
.ti -1c
.RI "static const char * \fBNumOfCSHasMu\fP = 'CSHasMu'"
.br
.RI "Number of call sites which have mu\&. "
.ti -1c
.RI "static const char * \fBNumOfLoadHasMu\fP = 'LoadHasMu'"
.br
.RI "Number of loads which have mu\&. "
.ti -1c
.RI "static const char * \fBNumOfStoreHasChi\fP = 'StoreHasChi'"
.br
.RI "Number of stores which have chi\&. "
.ti -1c
.RI "static const char * \fBNumOfBBHasMSSAPhi\fP = 'BBHasMSSAPhi'"
.br
.RI "Number of basic blocks which have mssa phi\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemSSAStat::MemSSAStat (\fBMemSSA\fP * memSSA)"
Constructor 
.SH "Member Function Documentation"
.PP 
.SS "void MemSSAStat::performStat ()\fC [virtual]\fP"
Start stating 
.PP
Reimplemented from \fBSVF::PTAStat\fP\&.
.SS "void MemSSAStat::printStat ()\fC [virtual]\fP"
Print statistics 
.SH "Member Data Documentation"
.PP 
.SS "const char * MemSSAStat::NumOfMSSAPhi = 'MSSAPhi'\fC [static]\fP"

.PP
Number of mssa phi\&. Number of non-top level ptr phi\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
