.TH "SVF::SCCDetection< GraphType >::GNodeSCCInfo" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SCCDetection< GraphType >::GNodeSCCInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBvisited\fP (void) const"
.br
.ti -1c
.RI "void \fBvisited\fP (bool v)"
.br
.ti -1c
.RI "bool \fBinSCC\fP (void) const"
.br
.ti -1c
.RI "void \fBinSCC\fP (bool v)"
.br
.ti -1c
.RI "NodeID \fBrep\fP (void) const"
.br
.ti -1c
.RI "void \fBrep\fP (NodeID n)"
.br
.ti -1c
.RI "void \fBaddSubNodes\fP (NodeID n)"
.br
.ti -1c
.RI "NodeBS & \fBsubNodes\fP ()"
.br
.ti -1c
.RI "const NodeBS & \fBsubNodes\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
