.TH "SVF::CommonCHGraph" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CommonCHGraph \- Common base for class hierarchy graph\&. Only implements what \fBPointerAnalysis\fP needs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CommonCHG\&.h>\fP
.PP
Inherited by \fBSVF::CHGraph\fP, and \fBSVF::DCHGraph\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCHGKind\fP { \fBStandard\fP, \fBDI\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBcsHasVFnsBasedonCHA\fP (CallSite cs)=0"
.br
.ti -1c
.RI "virtual const VFunSet & \fBgetCSVFsBasedonCHA\fP (CallSite cs)=0"
.br
.ti -1c
.RI "virtual bool \fBcsHasVtblsBasedonCHA\fP (CallSite cs)=0"
.br
.ti -1c
.RI "virtual const VTableSet & \fBgetCSVtblsBasedonCHA\fP (CallSite cs)=0"
.br
.ti -1c
.RI "virtual void \fBgetVFnsFromVtbls\fP (CallSite cs, const VTableSet &vtbls, VFunSet &virtualFunctions)=0"
.br
.ti -1c
.RI "CHGKind \fBgetKind\fP (void) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "CHGKind \fBkind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Common base for class hierarchy graph\&. Only implements what \fBPointerAnalysis\fP needs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
