.TH "SVF::GepValPN" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::GepValPN
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ValPN\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGepValPN\fP (const Value *val, NodeID i, const \fBLocationSet\fP &l, const Type *ty, u32_t idx)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "u32_t \fBgetOffset\fP () const"
.br
.RI "offset of the base value node "
.ti -1c
.RI "const std::string \fBgetValueName\fP () const"
.br
.RI "Return name of a LLVM value\&. "
.ti -1c
.RI "const Type * \fBgetType\fP () const"
.br
.RI "Return type of the value\&. "
.ti -1c
.RI "u32_t \fBgetFieldIdx\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGepValPN\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBValPN\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPAGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericPAGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
