.TH "SVF::IntraCFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::IntraCFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICFGEdge\&.h>\fP
.PP
Inherits \fBSVF::ICFGEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::pair< const Value *, NodeID > \fBBranchCondition\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraCFGEdge\fP (\fBICFGNode\fP *s, \fBICFGNode\fP *d)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBBranchCondition\fP & \fBgetBranchCondtion\fP ()"
.br
.ti -1c
.RI "void \fBsetBranchCondtion\fP (const Value *pNode, NodeID branchID)"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIntraCFGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBICFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericICFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Intra \fBICFG\fP edge representing control-flows between basic blocks within a function 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::pair<const Value*,NodeID> \fBSVF::IntraCFGEdge::BranchCondition\fP"
the first element is a boolean (for if/else) or numeric condition value (for switch) the second element is the value when this condition should hold to execute this CFGEdge\&. e\&.g\&., Inst1: br cmp label 0, label 1, Inst2 is label 0 and Inst 3 is label 1; for edge between Inst1 and Inst 2, the first element is cmp and second element is 0 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
