.TH "SVF::FSMPTA" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::FSMPTA
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FSMPTA\&.h>\fP
.PP
Inherits \fBSVF::FlowSensitive\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFSMPTA\fP (\fBMHP\fP *m, \fBLockAnalysis\fP *la)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~FSMPTA\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBinitialize\fP (\fBSVFModule\fP *module)"
.br
.RI "Initialize analysis\&. "
.ti -1c
.RI "\fBMHP\fP * \fBgetMHP\fP () const"
.br
.RI "Get \fBMHP\fP\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFSMPTA\fP * \fBcreateFSMPTA\fP (\fBSVFModule\fP *module, \fBMHP\fP *m, \fBLockAnalysis\fP *la)"
.br
.RI "Create signle instance of flow-sensitive pointer analysis\&. "
.ti -1c
.RI "static void \fBreleaseFSMPTA\fP ()"
.br
.RI "Release flow-sensitive pointer analysis\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Flow-sensitive pointer analysis for multithreaded programs 
.SH "Member Function Documentation"
.PP 
.SS "void FSMPTA::initialize (\fBSVFModule\fP * module)"

.PP
Initialize analysis\&. Initialize analysis 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
