.TH "SVF::InterMSSAPHISVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::InterMSSAPHISVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::MSSAPHISVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterMSSAPHISVFGNode\fP (NodeID id, const \fBFormalINSVFGNode\fP *fi)"
.br
.RI "Constructor interPHI for formal parameter\&. "
.ti -1c
.RI "\fBInterMSSAPHISVFGNode\fP (NodeID id, const \fBActualOUTSVFGNode\fP *ao)"
.br
.RI "Constructor interPHI for actual return\&. "
.ti -1c
.RI "bool \fBisFormalINPHI\fP () const"
.br
.ti -1c
.RI "bool \fBisActualOUTPHI\fP () const"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetFun\fP () const"
.br
.RI "Get the function of this SVFGNode\&. "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallSite\fP () const"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBInterMSSAPHISVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMSSAPHISVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMRSVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
