.TH "SVF::AndersenHLCD" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenHLCD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Andersen\&.h>\fP
.PP
Inherits \fBSVF::AndersenHCD\fP, and \fBSVF::AndersenLCD\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenHLCD\fP (\fBPAG\fP *_pag, \fBPTATY\fP type=\fBAndersenHLCD_WPA\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAndersenHLCD\fP * \fBcreateAndersenHLCD\fP (\fBPAG\fP *_pag)"
.br
.RI "Create an singleton instance directly instead of invoking llvm pass manager\&. "
.ti -1c
.RI "static void \fBreleaseAndersenHLCD\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBsolveWorklist\fP ()"
.br
.ti -1c
.RI "void \fBhandleCopyGep\fP (\fBConstraintNode\fP *node)"
.br
.ti -1c
.RI "void \fBmergeSCC\fP (NodeID nodeId)"
.br
.ti -1c
.RI "bool \fBmergeSrcToTgt\fP (NodeID nodeId, NodeID newRepId)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Hybrid Lazy Cycle Detection Based \fBAndersen\fP Analysis 
.SH "Member Function Documentation"
.PP 
.SS "void SVF::AndersenHLCD::handleCopyGep (\fBConstraintNode\fP * node)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
Process copy and gep edges 
.PP
Reimplemented from \fBSVF::AndersenLCD\fP\&.
.SS "void SVF::AndersenHLCD::initialize ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
\fBAndersenHCD\fP initilizer, including initilization of \fBPAG\fP, constraint graph and offline constraint graph 
.PP
Reimplemented from \fBSVF::AndersenHCD\fP\&.
.SS "void AndersenHLCD::mergeSCC (NodeID nodeId)\fC [protected]\fP, \fC [virtual]\fP"
Collapse nodes and fields based on the result of both offline and online SCC detection 
.PP
Reimplemented from \fBSVF::AndersenHCD\fP\&.
.SS "bool SVF::AndersenHLCD::mergeSrcToTgt (NodeID nodeId, NodeID newRepId)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
merge nodeId to newRepId\&. Return true if the newRepId is a PWC node union pts of node to rep
.PP
move the edges from node to rep, and remove the node
.PP
set rep and sub relations
.PP
Reimplemented from \fBSVF::AndersenLCD\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
