.TH "SVF::ThreadForkEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ThreadForkEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThreadCallGraph\&.h>\fP
.PP
Inherits \fBSVF::PTACallGraphEdge\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGenericNode\fP< \fBPTACallGraphNode\fP, \fBThreadForkEdge\fP >::GEdgeSetTy \fBForkEdgeSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadForkEdge\fP (\fBPTACallGraphNode\fP *s, \fBPTACallGraphNode\fP *d, CallSiteID csId)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~ThreadForkEdge\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBThreadForkEdge\fP *)"
.br
.RI "ClassOf\&. "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPTACallGraphEdge\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
PTA thread fork edge from fork site to the entry of a start routine function 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
