.TH "SVF::MSSADEF" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MSSADEF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSSAMuChi\&.h>\fP
.PP
Inherited by \fBSVF::MSSACHI< Cond >\fP, and \fBSVF::MSSAPHI< Cond >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDEFTYPE\fP { \fBSSACHI\fP, \fBStoreMSSACHI\fP, \fBCallMSSACHI\fP, \fBEntryMSSACHI\fP, \fBSSAPHI\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMSSADEF\fP (DEFTYPE t, const \fBMemRegion\fP *m)"
.br
.RI "Constructor/Destructer for \fBMSSADEF\fP\&. "
.ti -1c
.RI "const \fBMemRegion\fP * \fBgetMR\fP () const"
.br
.RI "Return memory region\&. "
.ti -1c
.RI "DEFTYPE \fBgetType\fP () const"
.br
.RI "Return type of this CHI\&. "
.ti -1c
.RI "void \fBsetResVer\fP (\fBMRVer\fP *v)"
.br
.RI "Set result operand ver\&. "
.ti -1c
.RI "\fBMRVer\fP * \fBgetResVer\fP () const"
.br
.RI "Set operand vers\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBMSSADEF\fP &rhs) const"
.br
.RI "Avoid adding duplicated chis and phis\&. "
.ti -1c
.RI "virtual void \fBdump\fP ()"
.br
.RI "Print MSSADef\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "DEFTYPE \fBtype\fP"
.br
.ti -1c
.RI "const \fBMemRegion\fP * \fBmr\fP"
.br
.ti -1c
.RI "\fBMRVer\fP * \fBresVer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Indirect Memory Definition 1) \fBMSSACHI\fP indirect memory object is modified a) \fBStoreCHI\fP definition at store b) \fBEntryCHI\fP definition at function entry 2) \fBMSSAPHI\fP memory object is defined at joint points of a control flow 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
