.TH "SVF::PAGBuilderFromFile" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::PAGBuilderFromFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PAGBuilderFromFile\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPAGBuilderFromFile\fP (std::string f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~PAGBuilderFromFile\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBPAG\fP * \fBgetPAG\fP () const"
.br
.RI "Return \fBPAG\fP\&. "
.ti -1c
.RI "std::string \fBgetFileName\fP () const"
.br
.RI "Return file name\&. "
.ti -1c
.RI "\fBPAG\fP * \fBbuild\fP ()"
.br
.RI "Start building\&. "
.ti -1c
.RI "void \fBaddEdge\fP (NodeID nodeSrc, NodeID nodeDst, Size_t offset, std::string edge)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build \fBPAG\fP from a user specified file (for debugging purpose) 
.SH "Member Function Documentation"
.PP 
.SS "void PAGBuilderFromFile::addEdge (NodeID srcID, NodeID dstID, Size_t offsetOrCSId, std::string edge)"
Add \fBPAG\fP edge according to a file format sanity check for \fBPAG\fP from txt
.SS "\fBPAG\fP * PAGBuilderFromFile::build ()"

.PP
Start building\&. new gep node's id from lower bound, nodeNum may not reflect the total nodes\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
