.TH "SVF::CxtStmtDPItem< LocCond >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CxtStmtDPItem< LocCond >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::StmtDPItem< LocCond >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCxtStmtDPItem\fP (const \fBCxtVar\fP &var, const LocCond *locCond)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCxtStmtDPItem\fP (const \fBCxtStmtDPItem\fP< LocCond > &dps)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "virtual \fB~CxtStmtDPItem\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBCxtVar\fP \fBgetCondVar\fP () const"
.br
.RI "Get context var\&. "
.ti -1c
.RI "const \fBContextCond\fP & \fBgetCond\fP () const"
.br
.RI "Get context\&. "
.ti -1c
.RI "\fBContextCond\fP & \fBgetCond\fP ()"
.br
.RI "Get context\&. "
.ti -1c
.RI "bool \fBpushContext\fP (NodeID cxt)"
.br
.RI "Push context\&. "
.ti -1c
.RI "bool \fBmatchContext\fP (NodeID cxt)"
.br
.RI "Match context\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCxtStmtDPItem\fP< LocCond > &rhs) const"
.br
.ti -1c
.RI "\fBCxtStmtDPItem\fP< LocCond > & \fBoperator=\fP (const \fBCxtStmtDPItem\fP< LocCond > &rhs)"
.br
.RI "Overloading operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCxtStmtDPItem\fP< LocCond > &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCxtStmtDPItem\fP< LocCond > &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "void \fBdump\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<class LocCond > bool \fBSVF::CxtStmtDPItem\fP< LocCond >::operator< (const \fBCxtStmtDPItem\fP< LocCond > & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
