.TH "SVF::SVFUtil::isa_impl< To, From, typename std::enable_if< std::is_base_of< To, From >::value >::type >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SVFUtil::isa_impl< To, From, typename std::enable_if< std::is_base_of< To, From >::value >::type > \- Always allow upcasts, and perform no dynamic check for them\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Casting\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBdoit\fP (const From &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename To, typename From>
.br
struct SVF::SVFUtil::isa_impl< To, From, typename std::enable_if< std::is_base_of< To, From >::value >::type >"
Always allow upcasts, and perform no dynamic check for them\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
