.TH "SVF::TypeAnalysis" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::TypeAnalysis
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::AndersenBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTypeAnalysis\fP (\fBPAG\fP *\fBpag\fP)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~TypeAnalysis\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBanalyze\fP ()"
.br
.RI "Type analysis\&. "
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.RI "Initialize analysis\&. "
.ti -1c
.RI "virtual void \fBfinalize\fP ()"
.br
.RI "Finalize analysis\&. "
.ti -1c
.RI "void \fBcallGraphSolveBasedOnCHA\fP (const CallSiteToFunPtrMap &callsites, CallEdgeMap &newEdges)"
.br
.RI "Resolve callgraph based on CHA\&. "
.ti -1c
.RI "void \fBdumpCHAStats\fP ()"
.br
.RI "Statistics of CHA and callgraph\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBTypeAnalysis\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPointerAnalysis\fP *pta)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
