.TH "SVF::MTAStat" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MTAStat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MTAStat\&.h>\fP
.PP
Inherits \fBSVF::PTAStat\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Set< const Instruction * > \fBInstSet\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMTAStat\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBperformThreadCallGraphStat\fP (\fBThreadCallGraph\fP *tcg)"
.br
.RI "Statistics for thread call graph\&. "
.ti -1c
.RI "void \fBperformTCTStat\fP (\fBTCT\fP *tct)"
.br
.RI "Statistics for thread creation tree\&. "
.ti -1c
.RI "void \fBperformMHPPairStat\fP (\fBMHP\fP *mhp, \fBLockAnalysis\fP *lsa)"
.br
.RI "Statistics for \fBMHP\fP statement pairs\&. "
.ti -1c
.RI "void \fBperformAnnotationStat\fP (\fBMTAAnnotator\fP *anno)"
.br
.RI "Statistics for annotation\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBTCTTime\fP"
.br
.ti -1c
.RI "double \fBMHPTime\fP"
.br
.ti -1c
.RI "double \fBFSMPTATime\fP"
.br
.ti -1c
.RI "double \fBAnnotationTime\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Statistics for \fBMTA\fP 
.SH "Member Function Documentation"
.PP 
.SS "void MTAStat::performMHPPairStat (\fBMHP\fP * mhp, \fBLockAnalysis\fP * lsa)"

.PP
Statistics for \fBMHP\fP statement pairs\&. Iterate every memory access pairs write vs read write vs write 
.SS "void MTAStat::performThreadCallGraphStat (\fBThreadCallGraph\fP * tcg)"

.PP
Statistics for thread call graph\&. Statistics for thread call graph 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
