.TH "SVF::StInfo" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::StInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemModel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStInfo\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~StInfo\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const llvm::Type * \fBgetFieldTypeWithFldIdx\fP (u32_t fldIdx)"
.br
.RI "Get method for fields of a struct\&. "
.ti -1c
.RI "const llvm::Type * \fBgetFieldTypeWithByteOffset\fP (u32_t offset)"
.br
.ti -1c
.RI "std::vector< u32_t > & \fBgetFieldIdxVec\fP ()"
.br
.ti -1c
.RI "std::vector< u32_t > & \fBgetFieldOffsetVec\fP ()"
.br
.ti -1c
.RI "std::vector< \fBFieldInfo\fP > & \fBgetFlattenFieldInfoVec\fP ()"
.br
.ti -1c
.RI "void \fBaddFldWithType\fP (u32_t fldIdx, u32_t offset, const llvm::Type *type)"
.br
.RI "Add field (index and offset) with its corresponding type\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetMaxFieldLimit\fP (u32_t limit)"
.br
.ti -1c
.RI "static u32_t \fBgetMaxFieldLimit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct information 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
