.TH "SVF::LockValidator" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::LockValidator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRaceResultValidator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLockValidator\fP (\fBLockAnalysis\fP *ls)"
.br
.ti -1c
.RI "bool \fBprotectedByCommonLocks\fP (const Instruction *I1, const Instruction *I2)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
