.TH "SVF::CallMU< Cond >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CallMU< Cond >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSSAMuChi\&.h>\fP
.PP
Inherits \fBSVF::MSSAMU< Cond >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallMU\fP (const \fBCallBlockNode\fP *cs, const \fBMemRegion\fP *m, Cond c=PathCondAllocator::trueCond())"
.br
.RI "Constructor/Destructor for MU\&. "
.ti -1c
.RI "const \fBCallBlockNode\fP * \fBgetCallSite\fP () const"
.br
.RI "Return callsite\&. "
.ti -1c
.RI "const BasicBlock * \fBgetBasicBlock\fP () const"
.br
.RI "Return basic block\&. "
.ti -1c
.RI "virtual void \fBdump\fP ()"
.br
.RI "Print MU\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCallMU\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBMSSAMU\fP< Cond > *mu)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class Cond>
.br
class SVF::CallMU< Cond >"
\fBCallMU\fP is annotated at callsite, representing a memory object is indirect read by callee 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
