.TH "SVF::CxtProc" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CxtProc
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CxtStmt\&.h>\fP
.PP
Inherited by \fBSVF::CxtThreadProc\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCxtProc\fP (const CallStrCxt &c, const \fBSVFFunction\fP *f)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCxtProc\fP (const \fBCxtProc\fP &ctm)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "virtual \fB~CxtProc\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetProc\fP () const"
.br
.RI "Return current procedure\&. "
.ti -1c
.RI "const CallStrCxt & \fBgetContext\fP () const"
.br
.RI "Return current context\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCxtProc\fP &rhs) const"
.br
.ti -1c
.RI "\fBCxtProc\fP & \fBoperator=\fP (const \fBCxtProc\fP &rhs)"
.br
.RI "Overloading operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCxtProc\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCxtProc\fP &rhs) const"
.br
.RI "Overloading operator==\&. "
.ti -1c
.RI "std::string \fBcxtToStr\fP () const"
.br
.RI "Return context in string format\&. "
.ti -1c
.RI "void \fBdump\fP () const"
.br
.RI "Dump \fBCxtProc\fP\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "CallStrCxt \fBcxt\fP"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBfun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Context-sensitive procedure <c,m> c represent current context m represent current procedure 
.SH "Member Function Documentation"
.PP 
.SS "bool SVF::CxtProc::operator< (const \fBCxtProc\fP & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
