.TH "SVF::IteratedDominanceFrontier" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::IteratedDominanceFrontier
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataFlowUtil\&.h>\fP
.PP
Inherits llvm::DominanceFrontierBase< BasicBlock, false >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBgetAnalysisUsage\fP (AnalysisUsage &AU) const"
.br
.ti -1c
.RI "iterator \fBgetIDFSet\fP (BasicBlock *B)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static char \fBID\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Iterated dominance frontier 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
