.TH "SVF::LocObjTypeInfo" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::LocObjTypeInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::ObjTypeInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocObjTypeInfo\fP (const Value *val, Type *t, Size_t max)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~LocObjTypeInfo\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "u32_t \fBgetObjSize\fP (const Value *val)"
.br
.RI "Get the size of this object\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "u32_t LocObjTypeInfo::getObjSize (const Value * val)\fC [virtual]\fP"

.PP
Get the size of this object\&. Get the size of this object 
.PP
Reimplemented from \fBSVF::ObjTypeInfo\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
