.TH "SVF::WPAFSSolver< GraphType >" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::WPAFSSolver< GraphType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WPAFSSolver\&.h>\fP
.PP
Inherits \fBSVF::WPASolver< GraphType >\fP\&.
.PP
Inherited by \fBSVF::FlowSensitive\fP, and \fBSVF::WPASCCSolver< GraphType >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWPAFSSolver\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~WPAFSSolver\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "virtual NodeID \fBsccRepNode\fP (NodeID id) const"
.br
.RI "SCC methods\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual NodeStack & \fBSCCDetect\fP ()"
.br
.RI "SCC detection\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NodeStack \fBnodeStack\fP"
.br
.RI "stack used for processing nodes\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class GraphType>
.br
class SVF::WPAFSSolver< GraphType >"
Flow-sensitive Solver 
.SH "Member Function Documentation"
.PP 
.SS "template<class GraphType > virtual NodeStack& \fBSVF::WPAFSSolver\fP< GraphType >::SCCDetect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
SCC detection\&. SCC detection
.PP
Both rep and sub nodes need to be processed later\&. Collect sub nodes from SCCDetector\&.
.PP
restore the topological order\&.
.PP
Reimplemented from \fBSVF::WPASolver< GraphType >\fP\&.
.PP
Reimplemented in \fBSVF::FlowSensitive\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
