.TH "SVF::CopyCGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CopyCGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConsGEdge\&.h>\fP
.PP
Inherits \fBSVF::ConstraintEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCopyCGEdge\fP (\fBConstraintNode\fP *s, \fBConstraintNode\fP *d, EdgeID id)"
.br
.RI "constructor "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBCopyCGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBConstraintEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericConsEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Copy edge 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
