.TH "SVF::CxtDPItem" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::CxtDPItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::DPItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCxtDPItem\fP (NodeID c, const \fBContextCond\fP &cxt)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCxtDPItem\fP (const \fBCxtVar\fP &var)"
.br
.ti -1c
.RI "\fBCxtDPItem\fP (const \fBCxtDPItem\fP &dps)"
.br
.RI "Copy constructor\&. "
.ti -1c
.RI "virtual \fB~CxtDPItem\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "const \fBContextCond\fP & \fBgetContexts\fP () const"
.br
.RI "Get context\&. "
.ti -1c
.RI "void \fBpushContext\fP (NodeID cxt)"
.br
.RI "Push context\&. "
.ti -1c
.RI "virtual bool \fBmatchContext\fP (NodeID cxt)"
.br
.RI "Match context\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCxtDPItem\fP &rhs) const"
.br
.ti -1c
.RI "\fBCxtDPItem\fP & \fBoperator=\fP (const \fBCxtDPItem\fP &rhs)"
.br
.RI "Overloading Operator=\&. "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCxtDPItem\fP &rhs) const"
.br
.RI "Overloading Operator==\&. "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCxtDPItem\fP &rhs) const"
.br
.RI "Overloading Operator!=\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool SVF::CxtDPItem::operator< (const \fBCxtDPItem\fP & rhs) const\fC [inline]\fP"
Enable compare operator to avoid duplicated item insertion in map or set to be noted that two vectors can also overload operator() 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
