.TH "SVF::ThreadMHPIndSVFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::ThreadMHPIndSVFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SVFGEdge\&.h>\fP
.PP
Inherits \fBSVF::IndirectSVFGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadMHPIndSVFGEdge\fP (\fBVFGNode\fP *s, \fBVFGNode\fP *d)"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBThreadMHPIndSVFGEdge\fP *)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIndirectSVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBMHP\fP \fBSVFG\fP edge representing indirect value-flows between two memory access may-happen-in-parallel in multithreaded program 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
