.TH "SVF::DirectSVFGEdge" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DirectSVFGEdge
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VFGEdge\&.h>\fP
.PP
Inherits \fBSVF::VFGEdge\fP\&.
.PP
Inherited by \fBSVF::CallDirSVFGEdge\fP, \fBSVF::IntraDirSVFGEdge\fP, and \fBSVF::RetDirSVFGEdge\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectSVFGEdge\fP (\fBVFGNode\fP *s, \fBVFGNode\fP *d, \fBGEdgeFlag\fP k)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBDirectSVFGEdge\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGEdge\fP *edge)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGEdgeTy\fP *edge)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSVFG\fP edge representing direct value-flows 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
