.TH "SVF::SaberAnnotator" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::SaberAnnotator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SaberAnnotator\&.h>\fP
.PP
Inherits \fBSVF::Annotator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaberAnnotator\fP (\fBProgSlice\fP *slice)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~SaberAnnotator\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "void \fBannotateSource\fP ()"
.br
.RI "Annotation\&. "
.ti -1c
.RI "void \fBannotateSinks\fP ()"
.br
.ti -1c
.RI "void \fBannotateFeasibleBranch\fP (const BranchInst *brInst, u32_t succPos)"
.br
.ti -1c
.RI "void \fBannotateInfeasibleBranch\fP (const BranchInst *brInst, u32_t succPos)"
.br
.ti -1c
.RI "void \fBannotateSwitch\fP (SwitchInst *brInst, u32_t succPos)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Saber annotation 
.SH "Member Function Documentation"
.PP 
.SS "void SaberAnnotator::annotateFeasibleBranch (const BranchInst * brInst, u32_t succPos)"
Annotate branch instruction and its corresponding feasible path 
.SS "void SaberAnnotator::annotateInfeasibleBranch (const BranchInst * brInst, u32_t succPos)"
Annotate branch instruction and its corresponding infeasible path 
.SS "void SaberAnnotator::annotateSwitch (SwitchInst * switchInst, u32_t succPos)"
Annotate switch instruction and its corresponding feasible path 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
