.TH "SVF::AndersenHCD" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::AndersenHCD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Andersen\&.h>\fP
.PP
Inherits \fBSVF::Andersen\fP\&.
.PP
Inherited by \fBSVF::AndersenHLCD\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSCCDetection\fP< \fBOfflineConsG\fP * > \fBOSCC\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAndersenHCD\fP (\fBPAG\fP *_pag, \fBPTATY\fP type=\fBAndersenHCD_WPA\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAndersenHCD\fP * \fBcreateAndersenHCD\fP (\fBPAG\fP *_pag)"
.br
.RI "Create an singleton instance directly instead of invoking llvm pass manager\&. "
.ti -1c
.RI "static void \fBreleaseAndersenHCD\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinitialize\fP ()"
.br
.ti -1c
.RI "bool \fBhasOfflineRep\fP (NodeID nodeId) const"
.br
.ti -1c
.RI "NodeID \fBgetOfflineRep\fP (NodeID nodeId)"
.br
.ti -1c
.RI "bool \fBisaMergedNode\fP (NodeID node) const"
.br
.ti -1c
.RI "void \fBsetMergedNode\fP (NodeID node)"
.br
.ti -1c
.RI "virtual void \fBsolveWorklist\fP ()"
.br
.ti -1c
.RI "virtual void \fBmergeSCC\fP (NodeID nodeId)"
.br
.ti -1c
.RI "void \fBmergeNodeAndPts\fP (NodeID node, NodeID tgt)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Hybrid Cycle Detection Based \fBAndersen\fP Analysis 
.SH "Member Function Documentation"
.PP 
.SS "void AndersenHCD::initialize ()\fC [protected]\fP, \fC [virtual]\fP"
\fBAndersenHCD\fP initilizer, including initilization of \fBPAG\fP, constraint graph and offline constraint graph 
.PP
Reimplemented from \fBSVF::Andersen\fP\&.
.PP
Reimplemented in \fBSVF::AndersenHLCD\fP\&.
.SS "void AndersenHCD::mergeNodeAndPts (NodeID node, NodeID rep)\fC [protected]\fP"
Merge node and its pts to the rep node 
.SS "void AndersenHCD::mergeSCC (NodeID nodeId)\fC [protected]\fP, \fC [virtual]\fP"
Collapse a node to its ref, if the ref exists 
.PP
Reimplemented in \fBSVF::AndersenHLCD\fP\&.
.SS "void AndersenHCD::solveWorklist ()\fC [protected]\fP, \fC [virtual]\fP"
\fBAndersenHCD\fP worklist solver 
.PP
Reimplemented from \fBSVF::WPASolver< GraphType >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
