.TH "SVF::LoadVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::LoadVFGNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <VFGNode\&.h>\fP
.PP
Inherits \fBSVF::StmtVFGNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadVFGNode\fP (NodeID id, const \fBLoadPE\fP *edge)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBLoadVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBStmtVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBVFGNode\fP for loads 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
