.TH "SVF::DDAClient" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::DDAClient
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DDAClient\&.h>\fP
.PP
Inherited by \fBSVF::AliasDDAClient\fP, and \fBSVF::FunptrDDAClient\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDDAClient\fP (\fBSVFModule\fP *mod)"
.br
.ti -1c
.RI "virtual void \fBinitialise\fP (\fBSVFModule\fP *)"
.br
.ti -1c
.RI "virtual OrderedNodeSet & \fBcollectCandidateQueries\fP (\fBPAG\fP *p)"
.br
.RI "Collect candidate pointers for query\&. "
.ti -1c
.RI "const OrderedNodeSet & \fBgetCandidateQueries\fP () const"
.br
.RI "Get candidate queries\&. "
.ti -1c
.RI "virtual void \fBhandleStatement\fP (const \fBSVFGNode\fP *, NodeID)"
.br
.RI "Call back used by \fBDDAVFSolver\fP\&. "
.ti -1c
.RI "void \fBsetPAG\fP (\fBPAG\fP *g)"
.br
.RI "Set \fBPAG\fP graph\&. "
.ti -1c
.RI "void \fBsetCurrentQueryPtr\fP (NodeID ptr)"
.br
.RI "Set the pointer being queried\&. "
.ti -1c
.RI "void \fBsetQuery\fP (NodeID ptr)"
.br
.RI "Set pointer to be queried by DDA analysis\&. "
.ti -1c
.RI "\fBSVFModule\fP * \fBgetModule\fP () const"
.br
.RI "Get LLVM module\&. "
.ti -1c
.RI "virtual void \fBanswerQueries\fP (\fBPointerAnalysis\fP *pta)"
.br
.ti -1c
.RI "virtual void \fBperformStat\fP (\fBPointerAnalysis\fP *)"
.br
.ti -1c
.RI "virtual void \fBcollectWPANum\fP (\fBSVFModule\fP *)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddCandidate\fP (NodeID id)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPAG\fP * \fBpag\fP"
.br
.RI "\fBPAG\fP graph used by current DDA analysis\&. "
.ti -1c
.RI "\fBSVFModule\fP * \fBmodule\fP"
.br
.RI "LLVM module\&. "
.ti -1c
.RI "NodeID \fBcurPtr\fP"
.br
.RI "current pointer being queried "
.ti -1c
.RI "OrderedNodeSet \fBcandidateQueries\fP"
.br
.RI "store all candidate pointers to be queried "
.in -1c
.SH "Detailed Description"
.PP 
General \fBDDAClient\fP which queries all top level pointers by default\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
