.TH "SVF::MTASVFGBuilder" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MTASVFGBuilder
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FSMPTA\&.h>\fP
.PP
Inherits \fBSVF::SVFGBuilder\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef PointerAnalysis::CallSiteSet \fBCallSiteSet\fP"
.br
.ti -1c
.RI "typedef PointerAnalysis::CallEdgeMap \fBCallEdgeMap\fP"
.br
.ti -1c
.RI "typedef PointerAnalysis::FunctionSet \fBFunctionSet\fP"
.br
.ti -1c
.RI "typedef Set< const \fBSVFGNode\fP * > \fBSVFGNodeSet\fP"
.br
.ti -1c
.RI "typedef std::vector< const \fBSVFGNode\fP * > \fBSVFGNodeVec\fP"
.br
.ti -1c
.RI "typedef NodeBS \fBSVFGNodeIDSet\fP"
.br
.ti -1c
.RI "typedef Set< const Instruction * > \fBInstSet\fP"
.br
.ti -1c
.RI "typedef std::pair< NodeID, NodeID > \fBNodeIDPair\fP"
.br
.ti -1c
.RI "typedef std::pair< const \fBStmtSVFGNode\fP *, LockAnalysis::LockSpan > \fBSVFGNodeLockSpanPair\fP"
.br
.ti -1c
.RI "typedef Map< SVFGNodeLockSpanPair, bool > \fBPairToBoolMap\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMTASVFGBuilder\fP (\fBMHP\fP *m, \fBLockAnalysis\fP *la)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~MTASVFGBuilder\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static u32_t \fBnumOfNewSVFGEdges\fP = 0"
.br
.RI "Number of newly added \fBSVFG\fP edges\&. "
.ti -1c
.RI "static u32_t \fBnumOfRemovedSVFGEdges\fP = 0"
.br
.ti -1c
.RI "static u32_t \fBnumOfRemovedPTS\fP = 0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBbuildSVFG\fP ()"
.br
.RI "Re-write create \fBSVFG\fP method\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSVFG\fP builder for DDA 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
