.TH "SVF::IntraPHIVFGNode" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::IntraPHIVFGNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSVF::PHIVFGNode\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Map< u32_t, const \fBICFGNode\fP * > \fBOPIncomingBBs\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntraPHIVFGNode\fP (NodeID id, const \fBPAGNode\fP *r)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const \fBICFGNode\fP * \fBgetOpIncomingBB\fP (u32_t pos) const"
.br
.ti -1c
.RI "void \fBsetOpVerAndBB\fP (u32_t pos, const \fBPAGNode\fP *node, const \fBICFGNode\fP *bb)"
.br
.ti -1c
.RI "virtual const std::string \fBtoString\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBclassof\fP (const \fBIntraPHIVFGNode\fP *)"
.br
.RI "Methods for support type inquiry through isa, cast, and dyn_cast: "
.ti -1c
.RI "static bool \fBclassof\fP (const \fBPHIVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBVFGNode\fP *node)"
.br
.ti -1c
.RI "static bool \fBclassof\fP (const \fBGenericVFGNodeTy\fP *node)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
