.TH "SVF::MemSSADF" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::MemSSADF
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SVFGBuilder\&.h>\fP
.PP
Inherits DominanceFrontier\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBrunOnDT\fP (DominatorTree &dt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dominator frontier used in MSSA 

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
