.TH "SVF::LLVMModuleSet" 3 "Sun Feb 14 2021" "SVF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVF::LLVMModuleSet
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< const \fBSVFFunction\fP * > \fBFunctionSetType\fP"
.br
.ti -1c
.RI "typedef Map< const \fBSVFFunction\fP *, const \fBSVFFunction\fP * > \fBFunDeclToDefMapTy\fP"
.br
.ti -1c
.RI "typedef Map< const \fBSVFFunction\fP *, FunctionSetType > \fBFunDefToDeclsMapTy\fP"
.br
.ti -1c
.RI "typedef Map< const GlobalVariable *, GlobalVariable * > \fBGlobalDefToRepMapTy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVFModule\fP * \fBbuildSVFModule\fP (Module &mod)"
.br
.ti -1c
.RI "\fBSVFModule\fP * \fBbuildSVFModule\fP (const std::vector< std::string > &moduleNameVec)"
.br
.ti -1c
.RI "\fBSVFModule\fP * \fBgetSVFModule\fP ()"
.br
.ti -1c
.RI "u32_t \fBgetModuleNum\fP () const"
.br
.ti -1c
.RI "Module * \fBgetModule\fP (u32_t idx) const"
.br
.ti -1c
.RI "Module & \fBgetModuleRef\fP (u32_t idx) const"
.br
.ti -1c
.RI "void \fBdumpModulesToFile\fP (const std::string suffix)"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetSVFFunction\fP (const Function *fun) const"
.br
.ti -1c
.RI "bool \fBhasDefinition\fP (const Function *fun) const"
.br
.RI "Fun decl --> def\&. "
.ti -1c
.RI "bool \fBhasDefinition\fP (const \fBSVFFunction\fP *fun) const"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetDefinition\fP (const Function *fun) const"
.br
.ti -1c
.RI "const \fBSVFFunction\fP * \fBgetDefinition\fP (const \fBSVFFunction\fP *fun) const"
.br
.ti -1c
.RI "bool \fBhasDeclaration\fP (const Function *fun) const"
.br
.RI "Fun def --> decl\&. "
.ti -1c
.RI "bool \fBhasDeclaration\fP (const \fBSVFFunction\fP *fun) const"
.br
.ti -1c
.RI "const FunctionSetType & \fBgetDeclaration\fP (const Function *fun) const"
.br
.ti -1c
.RI "const FunctionSetType & \fBgetDeclaration\fP (const \fBSVFFunction\fP *fun) const"
.br
.ti -1c
.RI "bool \fBhasGlobalRep\fP (const GlobalVariable *val) const"
.br
.RI "Global to rep\&. "
.ti -1c
.RI "GlobalVariable * \fBgetGlobalRep\fP (const GlobalVariable *val) const"
.br
.ti -1c
.RI "Module * \fBgetMainLLVMModule\fP () const"
.br
.ti -1c
.RI "LLVMContext & \fBgetContext\fP () const"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "bool \fBallCTir\fP (void) const"
.br
.RI "Returns true if all LLVM modules are compiled with ctir\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLLVMModuleSet\fP * \fBgetLLVMModuleSet\fP ()"
.br
.ti -1c
.RI "static void \fBreleaseLLVMModuleSet\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SVF from the source code\&.
